
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.com.example.jpos_server: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/jpos
    username: wjscksgurdl
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated


jwt:
  secretKey: eed49feca6c39f970a2cb61eadabb6cc81448505fde4c6a7ae942a67dcd45015
  expiration: 86400000

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${CLEARDB_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
