## users


insert into user (user_id, user_pw, user_name) values ('Bess', 'Logg', 'blogg0');
insert into user (user_id, user_pw, user_name) values ('Rebeca', 'Yearns', 'ryearns1');
insert into user (user_id, user_pw, user_name) values ('Kane', 'Heinreich', 'kheinreich2');
insert into user (user_id, user_pw, user_name) values ('Livvy', 'George', 'lgeorge3');
insert into user (user_id, user_pw, user_name) values ('Otis', 'Abbs', 'oabbs4');
insert into user (user_id, user_pw, user_name) values ('Mel', 'Emma', 'memma5');
insert into user (user_id, user_pw, user_name) values ('Fayre', 'Rodrigo', 'frodrigo6');
insert into user (user_id, user_pw, user_name) values ('Stewart', 'Lauritsen', 'slauritsen7');
insert into user (user_id, user_pw, user_name) values ('Barnabe', 'Quincee', 'bquincee8');
insert into user (user_id, user_pw, user_name) values ('Emelda', 'Bremley', 'ebremley9');
insert into user (user_id, user_pw, user_name) values ('Aubrette', 'Faherty', 'afahertya');


## stores

insert into store (store_Name, latitude, longitude, user_id) values ('Yacero', 41.6528112, 123.3427328, 1);
insert into store (store_Name, latitude, longitude, user_id) values ('Linktype', 41.11023, 20.0866554, 1);
insert into store (store_Name, latitude, longitude, user_id) values ('Teklist', 39.2259226, 23.2195437, 1);
insert into store (store_Name, latitude, longitude, user_id) values ('Zoombeat', 44.1875931, -77.3882908, 4);
insert into store (store_Name, latitude, longitude, user_id) values ('Yata', 37.943121, 115.217658, 6);
insert into store (store_Name, latitude, longitude, user_id) values ('Brainsphere', 26.656649, 116.799278, 10);
insert into store (store_Name, latitude, longitude, user_id) values ('Kwilith', -6.279197, 106.832873, 7);
insert into store (store_Name, latitude, longitude, user_id) values ('Lazz', 5.1227373, 9.9520961, 2);
insert into store (store_Name, latitude, longitude, user_id) values ('Vimbo', 22.974898, 113.993115, 5);
insert into store (store_Name, latitude, longitude, user_id) values ('Meembee', 44.2452219, 43.0880662, 3);
insert into store (store_Name, latitude, longitude, user_id) values ('Gabvine', 6.1097207, 102.2462087, 5);
insert into store (store_Name, latitude, longitude, user_id) values ('Tavu', 6.7640051, 124.3754414, 8);
insert into store (store_Name, latitude, longitude, user_id) values ('Demimbu', 15.45417, 45.01667, 1);
insert into store (store_Name, latitude, longitude, user_id) values ('Youopia', 66.14511, -65.71252, 10);
insert into store (store_Name, latitude, longitude, user_id) values ('Rhyloo', 39.893212, 116.477516, 3);
insert into store (store_Name, latitude, longitude, user_id) values ('BlogXS', 48.35874, 118.14065, 7);
insert into store (store_Name, latitude, longitude, user_id) values ('Babbleset', 32.9566376, 11.8492577, 3);
insert into store (store_Name, latitude, longitude, user_id) values ('Cogibox', 34.7487164, 134.0793911, 10);
insert into store (store_Name, latitude, longitude, user_id) values ('Cogidoo', 22.4076256, -83.8473015, 7);
insert into store (store_Name, latitude, longitude, user_id) values ('Feedfire', 36.8539304, 115.989656, 6);

## seats

insert into seat (seat_Name, store_id) values ('Anaïs', 7);
insert into seat (seat_Name, store_id) values ('Pénélope', 18);
insert into seat (seat_Name, store_id) values ('Océanne', 8);
insert into seat (seat_Name, store_id) values ('Liè', 7);
insert into seat (seat_Name, store_id) values ('Björn', 4);
insert into seat (seat_Name, store_id) values ('Océane', 4);
insert into seat (seat_Name, store_id) values ('Almérinda', 4);
insert into seat (seat_Name, store_id) values ('Agnès', 1);
insert into seat (seat_Name, store_id) values ('Gösta', 16);
insert into seat (seat_Name, store_id) values ('Yáo', 9);
insert into seat (seat_Name, store_id) values ('Joséphine', 15);
insert into seat (seat_Name, store_id) values ('Miléna', 10);
insert into seat (seat_Name, store_id) values ('Loïs', 5);
insert into seat (seat_Name, store_id) values ('Cinéma', 9);
insert into seat (seat_Name, store_id) values ('Lén', 6);
insert into seat (seat_Name, store_id) values ('Camélia', 7);
insert into seat (seat_Name, store_id) values ('Valérie', 10);
insert into seat (seat_Name, store_id) values ('Illustrée', 1);
insert into seat (seat_Name, store_id) values ('Séréna', 13);
insert into seat (seat_Name, store_id) values ('Aí', 1);
insert into seat (seat_Name, store_id) values ('Maëly', 11);
insert into seat (seat_Name, store_id) values ('Inès', 5);
insert into seat (seat_Name, store_id) values ('Eléonore', 15);
insert into seat (seat_Name, store_id) values ('Ruì', 13);
insert into seat (seat_Name, store_id) values ('Yú', 18);
insert into seat (seat_Name, store_id) values ('Ruì', 4);
insert into seat (seat_Name, store_id) values ('Cloé', 11);
insert into seat (seat_Name, store_id) values ('Maïlys', 14);
insert into seat (seat_Name, store_id) values ('Angèle', 11);
insert into seat (seat_Name, store_id) values ('Clémence', 19);
insert into seat (seat_Name, store_id) values ('Yénora', 9);
insert into seat (seat_Name, store_id) values ('Lén', 4);
insert into seat (seat_Name, store_id) values ('Lèi', 8);
insert into seat (seat_Name, store_id) values ('Françoise', 1);
insert into seat (seat_Name, store_id) values ('Dà', 17);
insert into seat (seat_Name, store_id) values ('Marie-hélène', 3);
insert into seat (seat_Name, store_id) values ('Marylène', 17);
insert into seat (seat_Name, store_id) values ('Sélène', 16);
insert into seat (seat_Name, store_id) values ('Miléna', 14);
insert into seat (seat_Name, store_id) values ('Kuí', 14);
insert into seat (seat_Name, store_id) values ('Yóu', 13);
insert into seat (seat_Name, store_id) values ('Cloé', 5);
insert into seat (seat_Name, store_id) values ('Bérénice', 18);
insert into seat (seat_Name, store_id) values ('Intéressant', 7);
insert into seat (seat_Name, store_id) values ('Léane', 18);
insert into seat (seat_Name, store_id) values ('Gisèle', 5);
insert into seat (seat_Name, store_id) values ('Geneviève', 5);
insert into seat (seat_Name, store_id) values ('Stévina', 18);
insert into seat (seat_Name, store_id) values ('Håkan', 19);
insert into seat (seat_Name, store_id) values ('Illustrée', 8);
insert into seat (seat_Name, store_id) values ('Mélissandre', 16);
insert into seat (seat_Name, store_id) values ('Mén', 11);
insert into seat (seat_Name, store_id) values ('Görel', 4);
insert into seat (seat_Name, store_id) values ('Crééz', 9);
insert into seat (seat_Name, store_id) values ('Stéphanie', 7);
insert into seat (seat_Name, store_id) values ('Andrée', 17);
insert into seat (seat_Name, store_id) values ('Bérangère', 5);
insert into seat (seat_Name, store_id) values ('Hélène', 8);
insert into seat (seat_Name, store_id) values ('Björn', 15);
insert into seat (seat_Name, store_id) values ('Esbjörn', 17);
insert into seat (seat_Name, store_id) values ('Märta', 7);
insert into seat (seat_Name, store_id) values ('Kuí', 9);
insert into seat (seat_Name, store_id) values ('Amélie', 19);
insert into seat (seat_Name, store_id) values ('Marie-françoise', 12);
insert into seat (seat_Name, store_id) values ('Maëly', 9);
insert into seat (seat_Name, store_id) values ('Yè', 1);
insert into seat (seat_Name, store_id) values ('Méline', 13);
insert into seat (seat_Name, store_id) values ('Mélys', 18);
insert into seat (seat_Name, store_id) values ('Maï', 1);
insert into seat (seat_Name, store_id) values ('Desirée', 10);
insert into seat (seat_Name, store_id) values ('Angélique', 13);
insert into seat (seat_Name, store_id) values ('Ophélie', 14);
insert into seat (seat_Name, store_id) values ('Nélie', 1);
insert into seat (seat_Name, store_id) values ('Mylène', 19);
insert into seat (seat_Name, store_id) values ('Adélaïde', 7);
insert into seat (seat_Name, store_id) values ('Séverine', 5);
insert into seat (seat_Name, store_id) values ('Miléna', 11);
insert into seat (seat_Name, store_id) values ('Yáo', 9);
insert into seat (seat_Name, store_id) values ('Yénora', 9);
insert into seat (seat_Name, store_id) values ('Illustrée', 1);
insert into seat (seat_Name, store_id) values ('Eugénie', 10);
insert into seat (seat_Name, store_id) values ('Aurélie', 10);
insert into seat (seat_Name, store_id) values ('Gösta', 2);
insert into seat (seat_Name, store_id) values ('Salomé', 13);
insert into seat (seat_Name, store_id) values ('Eléa', 17);
insert into seat (seat_Name, store_id) values ('Océanne', 5);
insert into seat (seat_Name, store_id) values ('Camélia', 13);
insert into seat (seat_Name, store_id) values ('Yè', 11);
insert into seat (seat_Name, store_id) values ('Néhémie', 12);
insert into seat (seat_Name, store_id) values ('Gaïa', 5);
insert into seat (seat_Name, store_id) values ('Nélie', 17);
insert into seat (seat_Name, store_id) values ('Josée', 9);
insert into seat (seat_Name, store_id) values ('Maëlys', 15);
insert into seat (seat_Name, store_id) values ('Lèi', 3);
insert into seat (seat_Name, store_id) values ('Pélagie', 2);
insert into seat (seat_Name, store_id) values ('Maëline', 13);
insert into seat (seat_Name, store_id) values ('Maëlyss', 5);
insert into seat (seat_Name, store_id) values ('Estée', 15);
insert into seat (seat_Name, store_id) values ('Fèi', 10);
insert into seat (seat_Name, store_id) values ('Andrée', 4);
insert into seat (seat_Name, store_id) values ('Pò', 5);
insert into seat (seat_Name, store_id) values ('Vénus', 1);
insert into seat (seat_Name, store_id) values ('Mylène', 12);
insert into seat (seat_Name, store_id) values ('Aimée', 19);
insert into seat (seat_Name, store_id) values ('Intéressant', 15);
insert into seat (seat_Name, store_id) values ('Noëlla', 11);
insert into seat (seat_Name, store_id) values ('Françoise', 11);
insert into seat (seat_Name, store_id) values ('Kévina', 9);
insert into seat (seat_Name, store_id) values ('Néhémie', 9);
insert into seat (seat_Name, store_id) values ('Bénédicte', 19);
insert into seat (seat_Name, store_id) values ('Liè', 2);
insert into seat (seat_Name, store_id) values ('Nadège', 5);
insert into seat (seat_Name, store_id) values ('Loïc', 17);
insert into seat (seat_Name, store_id) values ('Cinéma', 2);
insert into seat (seat_Name, store_id) values ('Hélène', 7);
insert into seat (seat_Name, store_id) values ('Faîtes', 1);
insert into seat (seat_Name, store_id) values ('Dà', 11);
insert into seat (seat_Name, store_id) values ('Estée', 18);
insert into seat (seat_Name, store_id) values ('Cunégonde', 10);
insert into seat (seat_Name, store_id) values ('Géraldine', 19);
insert into seat (seat_Name, store_id) values ('Lèi', 14);
insert into seat (seat_Name, store_id) values ('Cunégonde', 19);
insert into seat (seat_Name, store_id) values ('Béatrice', 1);
insert into seat (seat_Name, store_id) values ('Göran', 14);
insert into seat (seat_Name, store_id) values ('Östen', 8);
insert into seat (seat_Name, store_id) values ('Rachèle', 17);
insert into seat (seat_Name, store_id) values ('Clélia', 1);
insert into seat (seat_Name, store_id) values ('Réservés', 13);
insert into seat (seat_Name, store_id) values ('Andréanne', 6);
insert into seat (seat_Name, store_id) values ('Yáo', 13);
insert into seat (seat_Name, store_id) values ('Lucrèce', 17);
insert into seat (seat_Name, store_id) values ('Léonore', 13);
insert into seat (seat_Name, store_id) values ('Mélia', 12);
insert into seat (seat_Name, store_id) values ('Dù', 5);
insert into seat (seat_Name, store_id) values ('Mélanie', 5);
insert into seat (seat_Name, store_id) values ('Camélia', 14);
insert into seat (seat_Name, store_id) values ('Eléonore', 9);
insert into seat (seat_Name, store_id) values ('Camélia', 18);
insert into seat (seat_Name, store_id) values ('Pélagie', 14);
insert into seat (seat_Name, store_id) values ('Marie-josée', 10);
insert into seat (seat_Name, store_id) values ('Lauréna', 10);
insert into seat (seat_Name, store_id) values ('Néhémie', 13);
insert into seat (seat_Name, store_id) values ('Estève', 7);
insert into seat (seat_Name, store_id) values ('Publicité', 1);
insert into seat (seat_Name, store_id) values ('Noëlla', 11);
insert into seat (seat_Name, store_id) values ('Loïca', 14);
insert into seat (seat_Name, store_id) values ('Pélagie', 1);
insert into seat (seat_Name, store_id) values ('Adélie', 2);
insert into seat (seat_Name, store_id) values ('Miléna', 6);
insert into seat (seat_Name, store_id) values ('Maëlla', 17);
insert into seat (seat_Name, store_id) values ('Méthode', 7);
insert into seat (seat_Name, store_id) values ('Chloé', 7);
insert into seat (seat_Name, store_id) values ('Nélie', 19);
insert into seat (seat_Name, store_id) values ('Yáo', 15);
insert into seat (seat_Name, store_id) values ('Táng', 14);
insert into seat (seat_Name, store_id) values ('Tú', 7);
insert into seat (seat_Name, store_id) values ('Kuí', 4);
insert into seat (seat_Name, store_id) values ('Táng', 11);
insert into seat (seat_Name, store_id) values ('Marie-thérèse', 5);
insert into seat (seat_Name, store_id) values ('Naëlle', 11);
insert into seat (seat_Name, store_id) values ('Néhémie', 3);
insert into seat (seat_Name, store_id) values ('Laurélie', 11);
insert into seat (seat_Name, store_id) values ('Lén', 13);
insert into seat (seat_Name, store_id) values ('Fèi', 8);
insert into seat (seat_Name, store_id) values ('Bérangère', 8);
insert into seat (seat_Name, store_id) values ('Océanne', 13);
insert into seat (seat_Name, store_id) values ('Anaël', 9);
insert into seat (seat_Name, store_id) values ('Cloé', 5);
insert into seat (seat_Name, store_id) values ('Gaëlle', 14);
insert into seat (seat_Name, store_id) values ('Vénus', 5);
insert into seat (seat_Name, store_id) values ('Tán', 11);
insert into seat (seat_Name, store_id) values ('Örjan', 1);
insert into seat (seat_Name, store_id) values ('Maéna', 8);
insert into seat (seat_Name, store_id) values ('Régine', 7);
insert into seat (seat_Name, store_id) values ('Bénédicte', 2);
insert into seat (seat_Name, store_id) values ('Anaïs', 14);
insert into seat (seat_Name, store_id) values ('Mà', 1);
insert into seat (seat_Name, store_id) values ('Judicaël', 1);
insert into seat (seat_Name, store_id) values ('Liè', 6);
insert into seat (seat_Name, store_id) values ('Mahélie', 5);
insert into seat (seat_Name, store_id) values ('Adèle', 11);
insert into seat (seat_Name, store_id) values ('Frédérique', 6);
insert into seat (seat_Name, store_id) values ('Torbjörn', 9);
insert into seat (seat_Name, store_id) values ('Yè', 5);
insert into seat (seat_Name, store_id) values ('Anaïs', 7);
insert into seat (seat_Name, store_id) values ('Kévina', 19);
insert into seat (seat_Name, store_id) values ('Zoé', 5);
insert into seat (seat_Name, store_id) values ('Edmée', 11);
insert into seat (seat_Name, store_id) values ('Maïlys', 13);
insert into seat (seat_Name, store_id) values ('Eléonore', 14);
insert into seat (seat_Name, store_id) values ('Loïca', 13);
insert into seat (seat_Name, store_id) values ('Åke', 15);
insert into seat (seat_Name, store_id) values ('Néhémie', 5);
insert into seat (seat_Name, store_id) values ('Gisèle', 9);
insert into seat (seat_Name, store_id) values ('Bérénice', 15);
insert into seat (seat_Name, store_id) values ('Bérénice', 10);
insert into seat (seat_Name, store_id) values ('Eliès', 8);
insert into seat (seat_Name, store_id) values ('Félicie', 10);
insert into seat (seat_Name, store_id) values ('Dà', 1);
insert into seat (seat_Name, store_id) values ('Hélène', 6);


## menus

insert into menu (menu_name, store_id, price) values ('Zaam-Dox', 8, 4413);
insert into menu (menu_name, store_id, price) values ('Transcof', 5, 957);
insert into menu (menu_name, store_id, price) values ('Viva', 19, 5313);
insert into menu (menu_name, store_id, price) values ('Lotlux', 2, 9049);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 17, 3520);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 1, 581);
insert into menu (menu_name, store_id, price) values ('Subin', 6, 8859);
insert into menu (menu_name, store_id, price) values ('It', 5, 2087);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 5, 930);
insert into menu (menu_name, store_id, price) values ('Subin', 3, 2035);
insert into menu (menu_name, store_id, price) values ('Fixflex', 19, 7607);
insert into menu (menu_name, store_id, price) values ('Alpha', 4, 509);
insert into menu (menu_name, store_id, price) values ('Lotstring', 18, 3040);
insert into menu (menu_name, store_id, price) values ('Sonsing', 15, 2510);
insert into menu (menu_name, store_id, price) values ('Fix San', 17, 6890);
insert into menu (menu_name, store_id, price) values ('Bitchip', 5, 9997);
insert into menu (menu_name, store_id, price) values ('Cookley', 1, 6396);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 1, 8492);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 4, 355);
insert into menu (menu_name, store_id, price) values ('Aerified', 1, 1719);
insert into menu (menu_name, store_id, price) values ('Bamity', 12, 8541);
insert into menu (menu_name, store_id, price) values ('Gembucket', 9, 554);
insert into menu (menu_name, store_id, price) values ('Gembucket', 3, 8191);
insert into menu (menu_name, store_id, price) values ('Zathin', 8, 2051);
insert into menu (menu_name, store_id, price) values ('Stronghold', 7, 7595);
insert into menu (menu_name, store_id, price) values ('Keylex', 18, 5469);
insert into menu (menu_name, store_id, price) values ('Matsoft', 16, 4583);
insert into menu (menu_name, store_id, price) values ('Zontrax', 7, 2306);
insert into menu (menu_name, store_id, price) values ('Sonsing', 15, 8738);
insert into menu (menu_name, store_id, price) values ('Konklab', 14, 3485);
insert into menu (menu_name, store_id, price) values ('Cookley', 4, 9327);
insert into menu (menu_name, store_id, price) values ('Zaam-Dox', 19, 3786);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 6, 1920);
insert into menu (menu_name, store_id, price) values ('Prodder', 3, 8948);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 6, 3493);
insert into menu (menu_name, store_id, price) values ('Aerified', 8, 283);
insert into menu (menu_name, store_id, price) values ('Konklux', 12, 3372);
insert into menu (menu_name, store_id, price) values ('Pannier', 10, 860);
insert into menu (menu_name, store_id, price) values ('Duobam', 8, 8058);
insert into menu (menu_name, store_id, price) values ('Subin', 16, 7190);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 14, 2177);
insert into menu (menu_name, store_id, price) values ('Konklux', 10, 363);
insert into menu (menu_name, store_id, price) values ('Rank', 13, 9903);
insert into menu (menu_name, store_id, price) values ('Otcom', 17, 3694);
insert into menu (menu_name, store_id, price) values ('Zontrax', 18, 6908);
insert into menu (menu_name, store_id, price) values ('Veribet', 16, 6575);
insert into menu (menu_name, store_id, price) values ('Job', 10, 5694);
insert into menu (menu_name, store_id, price) values ('Tampflex', 13, 5244);
insert into menu (menu_name, store_id, price) values ('Trippledex', 1, 1041);
insert into menu (menu_name, store_id, price) values ('Redhold', 4, 8912);
insert into menu (menu_name, store_id, price) values ('Trippledex', 7, 8484);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 9, 6202);
insert into menu (menu_name, store_id, price) values ('Stringtough', 11, 3598);
insert into menu (menu_name, store_id, price) values ('Zamit', 11, 6196);
insert into menu (menu_name, store_id, price) values ('Redhold', 4, 566);
insert into menu (menu_name, store_id, price) values ('Tampflex', 10, 4691);
insert into menu (menu_name, store_id, price) values ('Latlux', 2, 4974);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 10, 8667);
insert into menu (menu_name, store_id, price) values ('Tin', 11, 6220);
insert into menu (menu_name, store_id, price) values ('Bamity', 6, 6600);
insert into menu (menu_name, store_id, price) values ('Fixflex', 19, 5997);
insert into menu (menu_name, store_id, price) values ('Y-find', 4, 5098);
insert into menu (menu_name, store_id, price) values ('Alpha', 9, 2766);
insert into menu (menu_name, store_id, price) values ('Bitchip', 12, 3986);
insert into menu (menu_name, store_id, price) values ('Flexidy', 13, 4250);
insert into menu (menu_name, store_id, price) values ('Tresom', 1, 8240);
insert into menu (menu_name, store_id, price) values ('Viva', 18, 4499);
insert into menu (menu_name, store_id, price) values ('Transcof', 7, 6078);
insert into menu (menu_name, store_id, price) values ('Treeflex', 12, 5731);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 3, 8017);
insert into menu (menu_name, store_id, price) values ('Zathin', 10, 2917);
insert into menu (menu_name, store_id, price) values ('Tampflex', 18, 9046);
insert into menu (menu_name, store_id, price) values ('Konklab', 17, 586);
insert into menu (menu_name, store_id, price) values ('Konklab', 5, 4300);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 11, 8343);
insert into menu (menu_name, store_id, price) values ('Prodder', 17, 8025);
insert into menu (menu_name, store_id, price) values ('Flexidy', 19, 7606);
insert into menu (menu_name, store_id, price) values ('Zontrax', 13, 9318);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 18, 5279);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 14, 8206);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 11, 8088);
insert into menu (menu_name, store_id, price) values ('Ronstring', 17, 9054);
insert into menu (menu_name, store_id, price) values ('Stim', 6, 9120);
insert into menu (menu_name, store_id, price) values ('Redhold', 6, 7054);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 2, 8629);
insert into menu (menu_name, store_id, price) values ('Prodder', 15, 4642);
insert into menu (menu_name, store_id, price) values ('Bytecard', 6, 2980);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 19, 7824);
insert into menu (menu_name, store_id, price) values ('Viva', 17, 726);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 12, 5105);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 15, 5861);
insert into menu (menu_name, store_id, price) values ('Andalax', 17, 9797);
insert into menu (menu_name, store_id, price) values ('Sonair', 4, 4166);
insert into menu (menu_name, store_id, price) values ('Konklab', 4, 9358);
insert into menu (menu_name, store_id, price) values ('Regrant', 9, 6175);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 19, 3469);
insert into menu (menu_name, store_id, price) values ('Cardguard', 4, 9021);
insert into menu (menu_name, store_id, price) values ('Fixflex', 15, 132);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 10, 7093);
insert into menu (menu_name, store_id, price) values ('Alphazap', 1, 7257);
insert into menu (menu_name, store_id, price) values ('Alphazap', 17, 1592);
insert into menu (menu_name, store_id, price) values ('Duobam', 4, 6418);
insert into menu (menu_name, store_id, price) values ('Cookley', 3, 2945);
insert into menu (menu_name, store_id, price) values ('Temp', 4, 2048);
insert into menu (menu_name, store_id, price) values ('Home Ing', 14, 4866);
insert into menu (menu_name, store_id, price) values ('Treeflex', 7, 7644);
insert into menu (menu_name, store_id, price) values ('Fix San', 14, 3148);
insert into menu (menu_name, store_id, price) values ('Namfix', 12, 9120);
insert into menu (menu_name, store_id, price) values ('Trippledex', 1, 1100);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 19, 3306);
insert into menu (menu_name, store_id, price) values ('Home Ing', 3, 5102);
insert into menu (menu_name, store_id, price) values ('Prodder', 16, 230);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 14, 7921);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 11, 5897);
insert into menu (menu_name, store_id, price) values ('Aerified', 5, 5223);
insert into menu (menu_name, store_id, price) values ('Rank', 18, 2411);
insert into menu (menu_name, store_id, price) values ('Alpha', 9, 3965);
insert into menu (menu_name, store_id, price) values ('Gembucket', 2, 8164);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 2, 3400);
insert into menu (menu_name, store_id, price) values ('Zontrax', 12, 5764);
insert into menu (menu_name, store_id, price) values ('Lotstring', 16, 6692);
insert into menu (menu_name, store_id, price) values ('Transcof', 6, 8417);
insert into menu (menu_name, store_id, price) values ('Trippledex', 14, 3866);
insert into menu (menu_name, store_id, price) values ('Vagram', 4, 4551);
insert into menu (menu_name, store_id, price) values ('Otcom', 15, 990);
insert into menu (menu_name, store_id, price) values ('Keylex', 4, 7465);
insert into menu (menu_name, store_id, price) values ('Konklab', 14, 4969);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 19, 5796);
insert into menu (menu_name, store_id, price) values ('Transcof', 7, 9184);
insert into menu (menu_name, store_id, price) values ('Andalax', 5, 6214);
insert into menu (menu_name, store_id, price) values ('Alphazap', 14, 1299);
insert into menu (menu_name, store_id, price) values ('Fix San', 18, 7713);
insert into menu (menu_name, store_id, price) values ('Bamity', 12, 860);
insert into menu (menu_name, store_id, price) values ('Treeflex', 10, 2252);
insert into menu (menu_name, store_id, price) values ('Sonsing', 14, 9769);
insert into menu (menu_name, store_id, price) values ('Stringtough', 6, 8398);
insert into menu (menu_name, store_id, price) values ('Fintone', 17, 3558);
insert into menu (menu_name, store_id, price) values ('Sonair', 9, 1134);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 5, 3253);
insert into menu (menu_name, store_id, price) values ('Transcof', 11, 7791);
insert into menu (menu_name, store_id, price) values ('Matsoft', 19, 8007);
insert into menu (menu_name, store_id, price) values ('Transcof', 1, 4815);
insert into menu (menu_name, store_id, price) values ('Hatity', 19, 4882);
insert into menu (menu_name, store_id, price) values ('Zaam-Dox', 1, 2424);
insert into menu (menu_name, store_id, price) values ('Cardify', 5, 8098);
insert into menu (menu_name, store_id, price) values ('Andalax', 8, 371);
insert into menu (menu_name, store_id, price) values ('Span', 17, 7250);
insert into menu (menu_name, store_id, price) values ('Aerified', 7, 4923);
insert into menu (menu_name, store_id, price) values ('Zontrax', 1, 8367);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 1, 1335);
insert into menu (menu_name, store_id, price) values ('Vagram', 9, 6898);
insert into menu (menu_name, store_id, price) values ('It', 13, 3664);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 16, 1624);
insert into menu (menu_name, store_id, price) values ('Viva', 12, 9186);
insert into menu (menu_name, store_id, price) values ('Tresom', 13, 7873);
insert into menu (menu_name, store_id, price) values ('Veribet', 1, 6382);
insert into menu (menu_name, store_id, price) values ('Zontrax', 1, 6657);
insert into menu (menu_name, store_id, price) values ('Alpha', 5, 2367);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 19, 5750);
insert into menu (menu_name, store_id, price) values ('Domainer', 15, 8715);
insert into menu (menu_name, store_id, price) values ('Redhold', 7, 898);
insert into menu (menu_name, store_id, price) values ('Andalax', 15, 4863);
insert into menu (menu_name, store_id, price) values ('Subin', 14, 2778);
insert into menu (menu_name, store_id, price) values ('Stim', 8, 5739);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 19, 9257);
insert into menu (menu_name, store_id, price) values ('Bigtax', 5, 6803);
insert into menu (menu_name, store_id, price) values ('Home Ing', 5, 5335);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 12, 8907);
insert into menu (menu_name, store_id, price) values ('Stringtough', 14, 3434);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 4, 7874);
insert into menu (menu_name, store_id, price) values ('Cookley', 1, 7424);
insert into menu (menu_name, store_id, price) values ('Bigtax', 17, 9228);
insert into menu (menu_name, store_id, price) values ('Viva', 4, 4434);
insert into menu (menu_name, store_id, price) values ('Sonsing', 7, 4470);
insert into menu (menu_name, store_id, price) values ('Sonsing', 14, 8762);
insert into menu (menu_name, store_id, price) values ('Y-find', 1, 4810);
insert into menu (menu_name, store_id, price) values ('Fix San', 2, 9248);
insert into menu (menu_name, store_id, price) values ('It', 8, 4695);
insert into menu (menu_name, store_id, price) values ('Viva', 19, 9783);
insert into menu (menu_name, store_id, price) values ('Stringtough', 12, 4523);
insert into menu (menu_name, store_id, price) values ('Keylex', 2, 7319);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 11, 9194);
insert into menu (menu_name, store_id, price) values ('Sonsing', 13, 2228);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 9, 3028);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 2, 2776);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 12, 6889);
insert into menu (menu_name, store_id, price) values ('Ronstring', 6, 7609);
insert into menu (menu_name, store_id, price) values ('Overhold', 19, 9989);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 4, 1306);
insert into menu (menu_name, store_id, price) values ('Bitchip', 11, 755);
insert into menu (menu_name, store_id, price) values ('Biodex', 4, 8107);
insert into menu (menu_name, store_id, price) values ('Prodder', 18, 4450);
insert into menu (menu_name, store_id, price) values ('Konklab', 16, 2145);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 12, 6132);
insert into menu (menu_name, store_id, price) values ('Veribet', 1, 3544);
insert into menu (menu_name, store_id, price) values ('Domainer', 1, 2961);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 9, 6919);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 9, 4190);
insert into menu (menu_name, store_id, price) values ('Domainer', 14, 382);
insert into menu (menu_name, store_id, price) values ('Zamit', 7, 9239);
insert into menu (menu_name, store_id, price) values ('Domainer', 4, 2849);
insert into menu (menu_name, store_id, price) values ('Konklab', 16, 6192);
insert into menu (menu_name, store_id, price) values ('Konklab', 12, 3821);
insert into menu (menu_name, store_id, price) values ('Cookley', 3, 3232);
insert into menu (menu_name, store_id, price) values ('Veribet', 14, 812);
insert into menu (menu_name, store_id, price) values ('Bytecard', 8, 5175);
insert into menu (menu_name, store_id, price) values ('Matsoft', 1, 4616);
insert into menu (menu_name, store_id, price) values ('Asoka', 16, 512);
insert into menu (menu_name, store_id, price) values ('Fintone', 17, 4408);
insert into menu (menu_name, store_id, price) values ('Redhold', 9, 9087);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 1, 5094);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 11, 6679);
insert into menu (menu_name, store_id, price) values ('Fix San', 4, 263);
insert into menu (menu_name, store_id, price) values ('Asoka', 16, 7946);
insert into menu (menu_name, store_id, price) values ('Tampflex', 4, 3036);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 12, 5410);
insert into menu (menu_name, store_id, price) values ('Tin', 14, 1936);
insert into menu (menu_name, store_id, price) values ('Sonair', 18, 4631);
insert into menu (menu_name, store_id, price) values ('Temp', 5, 6792);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 10, 7355);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 6, 1797);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 17, 5240);
insert into menu (menu_name, store_id, price) values ('Tin', 18, 3121);
insert into menu (menu_name, store_id, price) values ('Otcom', 11, 2037);
insert into menu (menu_name, store_id, price) values ('It', 10, 6996);
insert into menu (menu_name, store_id, price) values ('Subin', 10, 4794);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 3, 1788);
insert into menu (menu_name, store_id, price) values ('Stronghold', 15, 2073);
insert into menu (menu_name, store_id, price) values ('Asoka', 19, 896);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 19, 9382);
insert into menu (menu_name, store_id, price) values ('Latlux', 1, 8474);
insert into menu (menu_name, store_id, price) values ('Latlux', 14, 5919);
insert into menu (menu_name, store_id, price) values ('Home Ing', 17, 5263);
insert into menu (menu_name, store_id, price) values ('Keylex', 14, 5635);
insert into menu (menu_name, store_id, price) values ('Alphazap', 19, 2586);
insert into menu (menu_name, store_id, price) values ('Latlux', 5, 6964);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 14, 9697);
insert into menu (menu_name, store_id, price) values ('Zoolab', 2, 6242);
insert into menu (menu_name, store_id, price) values ('Prodder', 2, 4875);
insert into menu (menu_name, store_id, price) values ('Konklab', 10, 6916);
insert into menu (menu_name, store_id, price) values ('Zathin', 17, 4724);
insert into menu (menu_name, store_id, price) values ('Opela', 17, 3664);
insert into menu (menu_name, store_id, price) values ('Asoka', 13, 545);
insert into menu (menu_name, store_id, price) values ('Temp', 6, 2682);
insert into menu (menu_name, store_id, price) values ('Temp', 1, 4081);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 9, 2164);
insert into menu (menu_name, store_id, price) values ('Y-find', 6, 9699);
insert into menu (menu_name, store_id, price) values ('Regrant', 13, 1310);
insert into menu (menu_name, store_id, price) values ('Biodex', 12, 258);
insert into menu (menu_name, store_id, price) values ('Latlux', 7, 5730);
insert into menu (menu_name, store_id, price) values ('Viva', 7, 8452);
insert into menu (menu_name, store_id, price) values ('Greenlam', 14, 1319);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 4, 7489);
insert into menu (menu_name, store_id, price) values ('Treeflex', 17, 2788);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 1, 9726);
insert into menu (menu_name, store_id, price) values ('Fix San', 1, 270);
insert into menu (menu_name, store_id, price) values ('Y-find', 18, 9415);
insert into menu (menu_name, store_id, price) values ('Fix San', 16, 2892);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 4, 1089);
insert into menu (menu_name, store_id, price) values ('Zoolab', 18, 5639);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 2, 2063);
insert into menu (menu_name, store_id, price) values ('Redhold', 19, 8514);
insert into menu (menu_name, store_id, price) values ('Keylex', 1, 751);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 9, 9233);
insert into menu (menu_name, store_id, price) values ('Job', 16, 9399);
insert into menu (menu_name, store_id, price) values ('Otcom', 10, 7119);
insert into menu (menu_name, store_id, price) values ('Sonsing', 19, 5761);
insert into menu (menu_name, store_id, price) values ('Asoka', 1, 4545);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 12, 8547);
insert into menu (menu_name, store_id, price) values ('Zoolab', 5, 4441);
insert into menu (menu_name, store_id, price) values ('Stronghold', 14, 2585);
insert into menu (menu_name, store_id, price) values ('It', 14, 9637);
insert into menu (menu_name, store_id, price) values ('Greenlam', 6, 6130);
insert into menu (menu_name, store_id, price) values ('Job', 14, 9928);
insert into menu (menu_name, store_id, price) values ('Fix San', 10, 9709);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 19, 4655);
insert into menu (menu_name, store_id, price) values ('Lotstring', 18, 353);
insert into menu (menu_name, store_id, price) values ('Treeflex', 7, 560);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 12, 3938);
insert into menu (menu_name, store_id, price) values ('Konklab', 4, 4871);
insert into menu (menu_name, store_id, price) values ('Fix San', 15, 7040);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 1, 9600);
insert into menu (menu_name, store_id, price) values ('Stronghold', 7, 7327);
insert into menu (menu_name, store_id, price) values ('Zaam-Dox', 3, 3116);
insert into menu (menu_name, store_id, price) values ('Treeflex', 6, 3372);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 16, 2205);
insert into menu (menu_name, store_id, price) values ('Konklux', 2, 9521);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 6, 6892);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 17, 9900);
insert into menu (menu_name, store_id, price) values ('Latlux', 18, 4842);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 9, 8446);
insert into menu (menu_name, store_id, price) values ('Trippledex', 8, 4999);
insert into menu (menu_name, store_id, price) values ('Stringtough', 18, 5190);
insert into menu (menu_name, store_id, price) values ('Aerified', 7, 2311);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 5, 3022);
insert into menu (menu_name, store_id, price) values ('Regrant', 6, 4867);
insert into menu (menu_name, store_id, price) values ('Gembucket', 1, 8083);
insert into menu (menu_name, store_id, price) values ('Otcom', 4, 7445);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 19, 3358);
insert into menu (menu_name, store_id, price) values ('Flexidy', 9, 2570);
insert into menu (menu_name, store_id, price) values ('Trippledex', 1, 2442);
insert into menu (menu_name, store_id, price) values ('Tampflex', 1, 3002);
insert into menu (menu_name, store_id, price) values ('Transcof', 15, 2533);
insert into menu (menu_name, store_id, price) values ('Asoka', 12, 517);
insert into menu (menu_name, store_id, price) values ('Subin', 15, 4529);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 6, 1934);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 9, 4417);
insert into menu (menu_name, store_id, price) values ('Kanlam', 3, 9558);
insert into menu (menu_name, store_id, price) values ('Asoka', 4, 1154);
insert into menu (menu_name, store_id, price) values ('Alphazap', 5, 2051);
insert into menu (menu_name, store_id, price) values ('Span', 6, 8037);
insert into menu (menu_name, store_id, price) values ('Job', 12, 9852);
insert into menu (menu_name, store_id, price) values ('Transcof', 6, 9903);
insert into menu (menu_name, store_id, price) values ('Tin', 14, 1367);
insert into menu (menu_name, store_id, price) values ('Job', 18, 107);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 8, 3014);
insert into menu (menu_name, store_id, price) values ('Veribet', 17, 4293);
insert into menu (menu_name, store_id, price) values ('Stronghold', 17, 1190);
insert into menu (menu_name, store_id, price) values ('Prodder', 18, 4669);
insert into menu (menu_name, store_id, price) values ('Otcom', 1, 9440);
insert into menu (menu_name, store_id, price) values ('Home Ing', 19, 696);
insert into menu (menu_name, store_id, price) values ('Matsoft', 10, 5061);
insert into menu (menu_name, store_id, price) values ('Bytecard', 1, 6646);
insert into menu (menu_name, store_id, price) values ('Lotstring', 11, 5727);
insert into menu (menu_name, store_id, price) values ('Andalax', 17, 2273);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 15, 9475);
insert into menu (menu_name, store_id, price) values ('Kanlam', 2, 749);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 18, 7797);
insert into menu (menu_name, store_id, price) values ('Konklux', 19, 8667);
insert into menu (menu_name, store_id, price) values ('Domainer', 7, 7145);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 15, 4350);
insert into menu (menu_name, store_id, price) values ('Gembucket', 1, 5716);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 4, 5635);
insert into menu (menu_name, store_id, price) values ('Subin', 19, 1086);
insert into menu (menu_name, store_id, price) values ('Opela', 1, 2601);
insert into menu (menu_name, store_id, price) values ('Tresom', 14, 6019);
insert into menu (menu_name, store_id, price) values ('Prodder', 4, 7291);
insert into menu (menu_name, store_id, price) values ('Zaam-Dox', 14, 9147);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 16, 8024);
insert into menu (menu_name, store_id, price) values ('Lotstring', 11, 9639);
insert into menu (menu_name, store_id, price) values ('Stronghold', 2, 4907);
insert into menu (menu_name, store_id, price) values ('Vagram', 16, 2893);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 2, 3839);
insert into menu (menu_name, store_id, price) values ('Bytecard', 13, 2486);
insert into menu (menu_name, store_id, price) values ('Cookley', 15, 5359);
insert into menu (menu_name, store_id, price) values ('Flexidy', 13, 4744);
insert into menu (menu_name, store_id, price) values ('Kanlam', 17, 8617);
insert into menu (menu_name, store_id, price) values ('Transcof', 14, 3991);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 9, 7551);
insert into menu (menu_name, store_id, price) values ('Trippledex', 11, 8331);
insert into menu (menu_name, store_id, price) values ('Zamit', 16, 1788);
insert into menu (menu_name, store_id, price) values ('Stronghold', 2, 6322);
insert into menu (menu_name, store_id, price) values ('Transcof', 1, 2042);
insert into menu (menu_name, store_id, price) values ('Ronstring', 2, 1267);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 18, 8388);
insert into menu (menu_name, store_id, price) values ('Bamity', 1, 2934);
insert into menu (menu_name, store_id, price) values ('Konklab', 7, 4581);
insert into menu (menu_name, store_id, price) values ('Biodex', 9, 8807);
insert into menu (menu_name, store_id, price) values ('Stringtough', 4, 6439);
insert into menu (menu_name, store_id, price) values ('Namfix', 14, 9054);
insert into menu (menu_name, store_id, price) values ('Alphazap', 6, 4847);
insert into menu (menu_name, store_id, price) values ('Stim', 2, 1688);
insert into menu (menu_name, store_id, price) values ('Bytecard', 16, 5125);
insert into menu (menu_name, store_id, price) values ('Cardguard', 7, 5409);
insert into menu (menu_name, store_id, price) values ('Stim', 6, 9488);
insert into menu (menu_name, store_id, price) values ('Konklux', 19, 8680);
insert into menu (menu_name, store_id, price) values ('Ronstring', 13, 3051);
insert into menu (menu_name, store_id, price) values ('It', 1, 5299);
insert into menu (menu_name, store_id, price) values ('It', 10, 946);
insert into menu (menu_name, store_id, price) values ('Alphazap', 9, 598);
insert into menu (menu_name, store_id, price) values ('Zontrax', 3, 4628);
insert into menu (menu_name, store_id, price) values ('Lotstring', 5, 5618);
insert into menu (menu_name, store_id, price) values ('Alpha', 19, 1794);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 15, 6369);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 12, 2103);
insert into menu (menu_name, store_id, price) values ('It', 18, 5296);
insert into menu (menu_name, store_id, price) values ('Sonair', 17, 6119);
insert into menu (menu_name, store_id, price) values ('Viva', 4, 2672);
insert into menu (menu_name, store_id, price) values ('Gembucket', 3, 3581);
insert into menu (menu_name, store_id, price) values ('Zamit', 13, 7546);
insert into menu (menu_name, store_id, price) values ('Hatity', 10, 2448);
insert into menu (menu_name, store_id, price) values ('Ronstring', 15, 7453);
insert into menu (menu_name, store_id, price) values ('Lotstring', 14, 3151);
insert into menu (menu_name, store_id, price) values ('Fix San', 2, 3709);
insert into menu (menu_name, store_id, price) values ('Bitchip', 7, 6858);
insert into menu (menu_name, store_id, price) values ('Greenlam', 9, 418);
insert into menu (menu_name, store_id, price) values ('Subin', 18, 3128);
insert into menu (menu_name, store_id, price) values ('Redhold', 6, 6085);
insert into menu (menu_name, store_id, price) values ('Keylex', 9, 8127);
insert into menu (menu_name, store_id, price) values ('Zoolab', 17, 1359);
insert into menu (menu_name, store_id, price) values ('Kanlam', 11, 6936);
insert into menu (menu_name, store_id, price) values ('Bitchip', 13, 9384);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 10, 2418);
insert into menu (menu_name, store_id, price) values ('Domainer', 1, 9339);
insert into menu (menu_name, store_id, price) values ('Flexidy', 9, 2199);
insert into menu (menu_name, store_id, price) values ('Transcof', 17, 4870);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 18, 1956);
insert into menu (menu_name, store_id, price) values ('Konklux', 9, 3722);
insert into menu (menu_name, store_id, price) values ('Bytecard', 6, 6303);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 19, 8159);
insert into menu (menu_name, store_id, price) values ('Treeflex', 1, 730);
insert into menu (menu_name, store_id, price) values ('Keylex', 19, 2262);
insert into menu (menu_name, store_id, price) values ('It', 17, 873);
insert into menu (menu_name, store_id, price) values ('Fix San', 1, 7120);
insert into menu (menu_name, store_id, price) values ('Namfix', 7, 9821);
insert into menu (menu_name, store_id, price) values ('Aerified', 5, 5764);
insert into menu (menu_name, store_id, price) values ('Hatity', 4, 7099);
insert into menu (menu_name, store_id, price) values ('Stringtough', 17, 6429);
insert into menu (menu_name, store_id, price) values ('Stringtough', 15, 2716);
insert into menu (menu_name, store_id, price) values ('Otcom', 11, 9857);
insert into menu (menu_name, store_id, price) values ('Zontrax', 2, 4101);
insert into menu (menu_name, store_id, price) values ('Temp', 1, 4184);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 19, 9357);
insert into menu (menu_name, store_id, price) values ('Alphazap', 4, 3170);
insert into menu (menu_name, store_id, price) values ('Viva', 3, 4759);
insert into menu (menu_name, store_id, price) values ('Rank', 4, 1340);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 15, 6557);
insert into menu (menu_name, store_id, price) values ('Temp', 1, 1814);
insert into menu (menu_name, store_id, price) values ('Biodex', 1, 8471);
insert into menu (menu_name, store_id, price) values ('Fix San', 1, 763);
insert into menu (menu_name, store_id, price) values ('Rank', 12, 1033);
insert into menu (menu_name, store_id, price) values ('Stronghold', 2, 8921);
insert into menu (menu_name, store_id, price) values ('Veribet', 6, 4225);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 7, 6996);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 16, 2402);
insert into menu (menu_name, store_id, price) values ('It', 5, 7310);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 5, 1835);
insert into menu (menu_name, store_id, price) values ('Latlux', 6, 7521);
insert into menu (menu_name, store_id, price) values ('Greenlam', 18, 5567);
insert into menu (menu_name, store_id, price) values ('Bitchip', 18, 413);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 8, 9899);
insert into menu (menu_name, store_id, price) values ('Transcof', 15, 2587);
insert into menu (menu_name, store_id, price) values ('It', 1, 177);
insert into menu (menu_name, store_id, price) values ('Regrant', 9, 1611);
insert into menu (menu_name, store_id, price) values ('Sonair', 5, 8105);
insert into menu (menu_name, store_id, price) values ('Vagram', 5, 3060);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 10, 6127);
insert into menu (menu_name, store_id, price) values ('Viva', 14, 3197);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 1, 4740);
insert into menu (menu_name, store_id, price) values ('Fixflex', 5, 3451);
insert into menu (menu_name, store_id, price) values ('Cardify', 8, 6251);
insert into menu (menu_name, store_id, price) values ('Stronghold', 8, 3867);
insert into menu (menu_name, store_id, price) values ('Tampflex', 15, 9663);
insert into menu (menu_name, store_id, price) values ('Transcof', 11, 6468);
insert into menu (menu_name, store_id, price) values ('Cardify', 19, 2533);
insert into menu (menu_name, store_id, price) values ('Asoka', 9, 2110);
insert into menu (menu_name, store_id, price) values ('Sonair', 12, 7614);
insert into menu (menu_name, store_id, price) values ('Tampflex', 18, 8965);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 19, 8016);
insert into menu (menu_name, store_id, price) values ('Duobam', 7, 4352);
insert into menu (menu_name, store_id, price) values ('Domainer', 3, 2173);
insert into menu (menu_name, store_id, price) values ('Temp', 10, 9255);
insert into menu (menu_name, store_id, price) values ('Gembucket', 1, 9290);
insert into menu (menu_name, store_id, price) values ('Regrant', 10, 6942);
insert into menu (menu_name, store_id, price) values ('Sonair', 17, 2426);
insert into menu (menu_name, store_id, price) values ('Tin', 1, 8568);
insert into menu (menu_name, store_id, price) values ('Zathin', 17, 357);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 4, 502);
insert into menu (menu_name, store_id, price) values ('Greenlam', 13, 2353);
insert into menu (menu_name, store_id, price) values ('Job', 12, 9972);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 2, 7817);
insert into menu (menu_name, store_id, price) values ('Latlux', 9, 7565);
insert into menu (menu_name, store_id, price) values ('Biodex', 3, 1046);
insert into menu (menu_name, store_id, price) values ('Veribet', 1, 4181);
insert into menu (menu_name, store_id, price) values ('Alpha', 7, 1262);
insert into menu (menu_name, store_id, price) values ('Cardguard', 2, 6284);
insert into menu (menu_name, store_id, price) values ('Tresom', 8, 8510);
insert into menu (menu_name, store_id, price) values ('Job', 3, 3190);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 3, 3159);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 19, 9407);
insert into menu (menu_name, store_id, price) values ('Bigtax', 13, 6003);
insert into menu (menu_name, store_id, price) values ('Cardify', 2, 7237);
insert into menu (menu_name, store_id, price) values ('Kanlam', 16, 4830);
insert into menu (menu_name, store_id, price) values ('Overhold', 15, 5464);
insert into menu (menu_name, store_id, price) values ('Alpha', 15, 8679);
insert into menu (menu_name, store_id, price) values ('Job', 19, 2880);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 2, 6392);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 9, 9708);
insert into menu (menu_name, store_id, price) values ('Zathin', 1, 1897);
insert into menu (menu_name, store_id, price) values ('Prodder', 6, 4782);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 16, 7256);
insert into menu (menu_name, store_id, price) values ('Ronstring', 6, 2138);
insert into menu (menu_name, store_id, price) values ('Cookley', 1, 3460);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 6, 5928);
insert into menu (menu_name, store_id, price) values ('Konklux', 15, 7223);
insert into menu (menu_name, store_id, price) values ('Zoolab', 9, 6876);
insert into menu (menu_name, store_id, price) values ('Matsoft', 7, 7295);
insert into menu (menu_name, store_id, price) values ('Temp', 11, 799);
insert into menu (menu_name, store_id, price) values ('Treeflex', 8, 6969);
insert into menu (menu_name, store_id, price) values ('Temp', 16, 4275);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 15, 557);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 17, 2056);
insert into menu (menu_name, store_id, price) values ('Konklux', 9, 3397);
insert into menu (menu_name, store_id, price) values ('Domainer', 4, 505);
insert into menu (menu_name, store_id, price) values ('Cardguard', 17, 6424);
insert into menu (menu_name, store_id, price) values ('Vagram', 4, 7119);
insert into menu (menu_name, store_id, price) values ('Alphazap', 7, 5179);
insert into menu (menu_name, store_id, price) values ('Biodex', 13, 6522);
insert into menu (menu_name, store_id, price) values ('Alpha', 19, 5720);
insert into menu (menu_name, store_id, price) values ('Duobam', 1, 107);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 16, 1038);
insert into menu (menu_name, store_id, price) values ('Bamity', 15, 5578);
insert into menu (menu_name, store_id, price) values ('Cardguard', 16, 6601);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 12, 9425);
insert into menu (menu_name, store_id, price) values ('Vagram', 13, 553);
insert into menu (menu_name, store_id, price) values ('Stim', 14, 179);
insert into menu (menu_name, store_id, price) values ('Overhold', 12, 8544);
insert into menu (menu_name, store_id, price) values ('Namfix', 15, 9883);
insert into menu (menu_name, store_id, price) values ('Cardify', 8, 798);
insert into menu (menu_name, store_id, price) values ('Cookley', 5, 6745);
insert into menu (menu_name, store_id, price) values ('Vagram', 9, 6441);
insert into menu (menu_name, store_id, price) values ('Temp', 17, 7628);
insert into menu (menu_name, store_id, price) values ('Lotstring', 19, 3802);
insert into menu (menu_name, store_id, price) values ('Viva', 11, 6037);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 2, 8226);
insert into menu (menu_name, store_id, price) values ('Gembucket', 10, 928);
insert into menu (menu_name, store_id, price) values ('Alpha', 11, 4417);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 2, 3716);
insert into menu (menu_name, store_id, price) values ('Ronstring', 4, 8599);
insert into menu (menu_name, store_id, price) values ('Temp', 15, 9544);
insert into menu (menu_name, store_id, price) values ('Stringtough', 18, 4746);
insert into menu (menu_name, store_id, price) values ('Greenlam', 4, 405);
insert into menu (menu_name, store_id, price) values ('Keylex', 13, 5791);
insert into menu (menu_name, store_id, price) values ('Alpha', 9, 417);
insert into menu (menu_name, store_id, price) values ('Tin', 8, 7497);
insert into menu (menu_name, store_id, price) values ('Stringtough', 18, 5884);
insert into menu (menu_name, store_id, price) values ('Zoolab', 11, 2382);
insert into menu (menu_name, store_id, price) values ('Transcof', 13, 4568);
insert into menu (menu_name, store_id, price) values ('Konklux', 15, 6953);
insert into menu (menu_name, store_id, price) values ('Latlux', 8, 2857);
insert into menu (menu_name, store_id, price) values ('Sonair', 5, 5824);
insert into menu (menu_name, store_id, price) values ('Vagram', 7, 6523);
insert into menu (menu_name, store_id, price) values ('Asoka', 2, 3643);
insert into menu (menu_name, store_id, price) values ('Latlux', 19, 6658);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 19, 9886);
insert into menu (menu_name, store_id, price) values ('Stronghold', 1, 6478);
insert into menu (menu_name, store_id, price) values ('Fix San', 1, 3105);
insert into menu (menu_name, store_id, price) values ('Tin', 9, 4035);
insert into menu (menu_name, store_id, price) values ('Lotlux', 13, 3093);
insert into menu (menu_name, store_id, price) values ('Pannier', 1, 8998);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 15, 875);
insert into menu (menu_name, store_id, price) values ('Alphazap', 1, 8716);
insert into menu (menu_name, store_id, price) values ('Sonair', 5, 3914);
insert into menu (menu_name, store_id, price) values ('Bigtax', 1, 7039);
insert into menu (menu_name, store_id, price) values ('It', 1, 7638);
insert into menu (menu_name, store_id, price) values ('Stronghold', 13, 8663);
insert into menu (menu_name, store_id, price) values ('Span', 19, 2008);
insert into menu (menu_name, store_id, price) values ('Stringtough', 12, 1789);
insert into menu (menu_name, store_id, price) values ('Viva', 10, 2397);
insert into menu (menu_name, store_id, price) values ('Bamity', 1, 3452);
insert into menu (menu_name, store_id, price) values ('Konklux', 1, 2571);
insert into menu (menu_name, store_id, price) values ('Aerified', 14, 9732);
insert into menu (menu_name, store_id, price) values ('Sonair', 11, 3038);
insert into menu (menu_name, store_id, price) values ('Cookley', 11, 4711);
insert into menu (menu_name, store_id, price) values ('Overhold', 10, 8432);
insert into menu (menu_name, store_id, price) values ('Veribet', 18, 7839);
insert into menu (menu_name, store_id, price) values ('Lotstring', 17, 3525);
insert into menu (menu_name, store_id, price) values ('Latlux', 3, 5203);
insert into menu (menu_name, store_id, price) values ('Bytecard', 16, 9648);
insert into menu (menu_name, store_id, price) values ('Overhold', 5, 3670);
insert into menu (menu_name, store_id, price) values ('Fintone', 11, 6065);
insert into menu (menu_name, store_id, price) values ('Konklux', 2, 7938);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 18, 6056);
insert into menu (menu_name, store_id, price) values ('Aerified', 14, 2116);
insert into menu (menu_name, store_id, price) values ('Pannier', 7, 4381);
insert into menu (menu_name, store_id, price) values ('Bigtax', 2, 8136);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 16, 7560);
insert into menu (menu_name, store_id, price) values ('Alpha', 16, 4720);
insert into menu (menu_name, store_id, price) values ('Latlux', 18, 9390);
insert into menu (menu_name, store_id, price) values ('Kanlam', 17, 403);
insert into menu (menu_name, store_id, price) values ('Fintone', 9, 1232);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 7, 4685);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 14, 5571);
insert into menu (menu_name, store_id, price) values ('Tin', 11, 3833);
insert into menu (menu_name, store_id, price) values ('Domainer', 2, 5109);
insert into menu (menu_name, store_id, price) values ('Zontrax', 17, 9617);
insert into menu (menu_name, store_id, price) values ('Bytecard', 8, 5970);
insert into menu (menu_name, store_id, price) values ('Matsoft', 13, 9649);
insert into menu (menu_name, store_id, price) values ('Tresom', 16, 7306);
insert into menu (menu_name, store_id, price) values ('Latlux', 6, 1883);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 1, 4943);
insert into menu (menu_name, store_id, price) values ('Y-find', 18, 9719);
insert into menu (menu_name, store_id, price) values ('Fix San', 4, 5446);
insert into menu (menu_name, store_id, price) values ('Opela', 10, 2751);
insert into menu (menu_name, store_id, price) values ('Aerified', 16, 6519);
insert into menu (menu_name, store_id, price) values ('Stringtough', 11, 8594);
insert into menu (menu_name, store_id, price) values ('Zathin', 16, 956);
insert into menu (menu_name, store_id, price) values ('Domainer', 19, 1972);
insert into menu (menu_name, store_id, price) values ('Prodder', 1, 8912);
insert into menu (menu_name, store_id, price) values ('Opela', 11, 1642);
insert into menu (menu_name, store_id, price) values ('Matsoft', 11, 6626);
insert into menu (menu_name, store_id, price) values ('Tresom', 18, 9140);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 6, 9944);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 6, 6935);
insert into menu (menu_name, store_id, price) values ('Stim', 1, 8242);
insert into menu (menu_name, store_id, price) values ('Ronstring', 5, 4314);
insert into menu (menu_name, store_id, price) values ('Stim', 4, 6748);
insert into menu (menu_name, store_id, price) values ('Lotlux', 17, 4594);
insert into menu (menu_name, store_id, price) values ('Bamity', 16, 6602);
insert into menu (menu_name, store_id, price) values ('Temp', 14, 2118);
insert into menu (menu_name, store_id, price) values ('Redhold', 11, 2940);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 6, 8247);
insert into menu (menu_name, store_id, price) values ('Flexidy', 16, 2008);
insert into menu (menu_name, store_id, price) values ('Cardguard', 19, 7311);
insert into menu (menu_name, store_id, price) values ('Greenlam', 6, 1357);
insert into menu (menu_name, store_id, price) values ('Fix San', 3, 5133);
insert into menu (menu_name, store_id, price) values ('Alphazap', 13, 9431);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 18, 469);
insert into menu (menu_name, store_id, price) values ('Job', 3, 6684);
insert into menu (menu_name, store_id, price) values ('Latlux', 18, 5438);
insert into menu (menu_name, store_id, price) values ('Bigtax', 18, 2582);
insert into menu (menu_name, store_id, price) values ('Viva', 3, 894);
insert into menu (menu_name, store_id, price) values ('Asoka', 8, 5937);
insert into menu (menu_name, store_id, price) values ('Veribet', 7, 2904);
insert into menu (menu_name, store_id, price) values ('Kanlam', 17, 1882);
insert into menu (menu_name, store_id, price) values ('Zoolab', 14, 6953);
insert into menu (menu_name, store_id, price) values ('Latlux', 11, 3293);
insert into menu (menu_name, store_id, price) values ('Opela', 13, 1108);
insert into menu (menu_name, store_id, price) values ('Cardify', 16, 4980);
insert into menu (menu_name, store_id, price) values ('Sonair', 10, 7100);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 7, 106);
insert into menu (menu_name, store_id, price) values ('Fix San', 8, 9035);
insert into menu (menu_name, store_id, price) values ('Otcom', 7, 3485);
insert into menu (menu_name, store_id, price) values ('Duobam', 5, 5224);
insert into menu (menu_name, store_id, price) values ('Span', 4, 4662);
insert into menu (menu_name, store_id, price) values ('Stringtough', 15, 5622);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 7, 6859);
insert into menu (menu_name, store_id, price) values ('Asoka', 6, 4829);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 7, 7028);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 14, 8120);
insert into menu (menu_name, store_id, price) values ('Tin', 3, 9211);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 18, 8604);
insert into menu (menu_name, store_id, price) values ('Temp', 18, 4336);
insert into menu (menu_name, store_id, price) values ('Gembucket', 6, 8484);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 1, 6497);
insert into menu (menu_name, store_id, price) values ('Otcom', 12, 3941);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 10, 3848);
insert into menu (menu_name, store_id, price) values ('Namfix', 13, 5999);
insert into menu (menu_name, store_id, price) values ('Greenlam', 8, 942);
insert into menu (menu_name, store_id, price) values ('Hatity', 18, 9709);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 9, 7585);
insert into menu (menu_name, store_id, price) values ('Stringtough', 8, 2983);
insert into menu (menu_name, store_id, price) values ('Matsoft', 19, 1716);
insert into menu (menu_name, store_id, price) values ('Fintone', 14, 2557);
insert into menu (menu_name, store_id, price) values ('Y-find', 10, 633);
insert into menu (menu_name, store_id, price) values ('Keylex', 2, 6989);
insert into menu (menu_name, store_id, price) values ('Voyatouch', 16, 3831);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 6, 4756);
insert into menu (menu_name, store_id, price) values ('Regrant', 15, 2228);
insert into menu (menu_name, store_id, price) values ('Cardguard', 16, 6355);
insert into menu (menu_name, store_id, price) values ('Gembucket', 9, 659);
insert into menu (menu_name, store_id, price) values ('Cookley', 7, 2302);
insert into menu (menu_name, store_id, price) values ('Bamity', 12, 5462);
insert into menu (menu_name, store_id, price) values ('Lotstring', 18, 1797);
insert into menu (menu_name, store_id, price) values ('Alpha', 9, 987);
insert into menu (menu_name, store_id, price) values ('Keylex', 14, 8213);
insert into menu (menu_name, store_id, price) values ('Pannier', 7, 837);
insert into menu (menu_name, store_id, price) values ('Redhold', 11, 7055);
insert into menu (menu_name, store_id, price) values ('Andalax', 15, 6182);
insert into menu (menu_name, store_id, price) values ('Kanlam', 13, 2994);
insert into menu (menu_name, store_id, price) values ('Namfix', 16, 9354);
insert into menu (menu_name, store_id, price) values ('Konklux', 6, 6574);
insert into menu (menu_name, store_id, price) values ('Tresom', 14, 3737);
insert into menu (menu_name, store_id, price) values ('Home Ing', 2, 7288);
insert into menu (menu_name, store_id, price) values ('Redhold', 17, 7646);
insert into menu (menu_name, store_id, price) values ('Rank', 3, 2323);
insert into menu (menu_name, store_id, price) values ('Tresom', 3, 2574);
insert into menu (menu_name, store_id, price) values ('Span', 9, 3027);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 15, 8446);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 7, 5042);
insert into menu (menu_name, store_id, price) values ('Keylex', 18, 8867);
insert into menu (menu_name, store_id, price) values ('Asoka', 7, 671);
insert into menu (menu_name, store_id, price) values ('Temp', 8, 6676);
insert into menu (menu_name, store_id, price) values ('Andalax', 13, 9809);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 19, 3758);
insert into menu (menu_name, store_id, price) values ('Gembucket', 17, 2314);
insert into menu (menu_name, store_id, price) values ('Alphazap', 6, 7749);
insert into menu (menu_name, store_id, price) values ('Konklux', 1, 4362);
insert into menu (menu_name, store_id, price) values ('Domainer', 12, 3985);
insert into menu (menu_name, store_id, price) values ('Lotlux', 3, 6343);
insert into menu (menu_name, store_id, price) values ('Vagram', 7, 9159);
insert into menu (menu_name, store_id, price) values ('Tin', 3, 3182);
insert into menu (menu_name, store_id, price) values ('Pannier', 12, 7889);
insert into menu (menu_name, store_id, price) values ('Duobam', 6, 3890);
insert into menu (menu_name, store_id, price) values ('Cookley', 8, 2525);
insert into menu (menu_name, store_id, price) values ('Bitchip', 16, 8924);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 16, 3494);
insert into menu (menu_name, store_id, price) values ('Cookley', 19, 4704);
insert into menu (menu_name, store_id, price) values ('Overhold', 4, 7540);
insert into menu (menu_name, store_id, price) values ('Andalax', 10, 708);
insert into menu (menu_name, store_id, price) values ('Gembucket', 11, 4301);
insert into menu (menu_name, store_id, price) values ('Alphazap', 17, 974);
insert into menu (menu_name, store_id, price) values ('It', 17, 5672);
insert into menu (menu_name, store_id, price) values ('Duobam', 15, 2154);
insert into menu (menu_name, store_id, price) values ('Trippledex', 17, 3596);
insert into menu (menu_name, store_id, price) values ('Keylex', 9, 5544);
insert into menu (menu_name, store_id, price) values ('Sonsing', 19, 4111);
insert into menu (menu_name, store_id, price) values ('Greenlam', 10, 2365);
insert into menu (menu_name, store_id, price) values ('Rank', 5, 7656);
insert into menu (menu_name, store_id, price) values ('Kanlam', 4, 2326);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 14, 6333);
insert into menu (menu_name, store_id, price) values ('Konklux', 3, 5646);
insert into menu (menu_name, store_id, price) values ('Kanlam', 3, 2116);
insert into menu (menu_name, store_id, price) values ('Zamit', 6, 5646);
insert into menu (menu_name, store_id, price) values ('Job', 3, 7957);
insert into menu (menu_name, store_id, price) values ('Bamity', 12, 4847);
insert into menu (menu_name, store_id, price) values ('Stronghold', 13, 8866);
insert into menu (menu_name, store_id, price) values ('Job', 16, 3416);
insert into menu (menu_name, store_id, price) values ('Keylex', 15, 5995);
insert into menu (menu_name, store_id, price) values ('Home Ing', 13, 991);
insert into menu (menu_name, store_id, price) values ('Asoka', 13, 9237);
insert into menu (menu_name, store_id, price) values ('Home Ing', 2, 2150);
insert into menu (menu_name, store_id, price) values ('Duobam', 7, 4039);
insert into menu (menu_name, store_id, price) values ('Tin', 19, 6942);
insert into menu (menu_name, store_id, price) values ('Zathin', 16, 8405);
insert into menu (menu_name, store_id, price) values ('Temp', 7, 4536);
insert into menu (menu_name, store_id, price) values ('Greenlam', 8, 4984);
insert into menu (menu_name, store_id, price) values ('Duobam', 15, 8346);
insert into menu (menu_name, store_id, price) values ('Trippledex', 3, 1195);
insert into menu (menu_name, store_id, price) values ('Overhold', 11, 7447);
insert into menu (menu_name, store_id, price) values ('Alpha', 18, 6417);
insert into menu (menu_name, store_id, price) values ('Namfix', 3, 3377);
insert into menu (menu_name, store_id, price) values ('Kanlam', 4, 9357);
insert into menu (menu_name, store_id, price) values ('Stringtough', 15, 8002);
insert into menu (menu_name, store_id, price) values ('Stim', 8, 2812);
insert into menu (menu_name, store_id, price) values ('Lotlux', 1, 8532);
insert into menu (menu_name, store_id, price) values ('Alpha', 4, 3644);
insert into menu (menu_name, store_id, price) values ('Asoka', 4, 5267);
insert into menu (menu_name, store_id, price) values ('Tin', 4, 8523);
insert into menu (menu_name, store_id, price) values ('Hatity', 5, 4685);
insert into menu (menu_name, store_id, price) values ('Kanlam', 13, 8957);
insert into menu (menu_name, store_id, price) values ('Bitchip', 16, 3933);
insert into menu (menu_name, store_id, price) values ('Opela', 6, 2270);
insert into menu (menu_name, store_id, price) values ('Trippledex', 13, 8746);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 15, 610);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 7, 6756);
insert into menu (menu_name, store_id, price) values ('Zaam-Dox', 1, 6834);
insert into menu (menu_name, store_id, price) values ('Stringtough', 1, 377);
insert into menu (menu_name, store_id, price) values ('Gembucket', 16, 6536);
insert into menu (menu_name, store_id, price) values ('Hatity', 18, 6302);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 4, 1335);
insert into menu (menu_name, store_id, price) values ('Span', 1, 3848);
insert into menu (menu_name, store_id, price) values ('Redhold', 19, 1882);
insert into menu (menu_name, store_id, price) values ('Namfix', 18, 9154);
insert into menu (menu_name, store_id, price) values ('Opela', 1, 4894);
insert into menu (menu_name, store_id, price) values ('Zoolab', 14, 1290);
insert into menu (menu_name, store_id, price) values ('Cookley', 4, 4623);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 9, 8031);
insert into menu (menu_name, store_id, price) values ('Home Ing', 2, 1281);
insert into menu (menu_name, store_id, price) values ('Redhold', 11, 4198);
insert into menu (menu_name, store_id, price) values ('Y-find', 14, 3655);
insert into menu (menu_name, store_id, price) values ('Gembucket', 9, 6653);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 12, 9442);
insert into menu (menu_name, store_id, price) values ('Konklab', 7, 2865);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 11, 1419);
insert into menu (menu_name, store_id, price) values ('Bytecard', 19, 378);
insert into menu (menu_name, store_id, price) values ('Biodex', 13, 371);
insert into menu (menu_name, store_id, price) values ('Opela', 10, 7675);
insert into menu (menu_name, store_id, price) values ('Span', 13, 1318);
insert into menu (menu_name, store_id, price) values ('Zathin', 8, 6642);
insert into menu (menu_name, store_id, price) values ('Tin', 11, 4094);
insert into menu (menu_name, store_id, price) values ('Kanlam', 14, 5182);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 14, 4131);
insert into menu (menu_name, store_id, price) values ('Kanlam', 19, 7986);
insert into menu (menu_name, store_id, price) values ('Veribet', 4, 6058);
insert into menu (menu_name, store_id, price) values ('Konklab', 14, 9542);
insert into menu (menu_name, store_id, price) values ('Fintone', 14, 6883);
insert into menu (menu_name, store_id, price) values ('Biodex', 3, 9086);
insert into menu (menu_name, store_id, price) values ('Job', 3, 5280);
insert into menu (menu_name, store_id, price) values ('Tin', 4, 6114);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 15, 3731);
insert into menu (menu_name, store_id, price) values ('Stringtough', 3, 1292);
insert into menu (menu_name, store_id, price) values ('It', 15, 6838);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 2, 2845);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 16, 4232);
insert into menu (menu_name, store_id, price) values ('Aerified', 2, 9174);
insert into menu (menu_name, store_id, price) values ('Zoolab', 7, 942);
insert into menu (menu_name, store_id, price) values ('Lotstring', 4, 1767);
insert into menu (menu_name, store_id, price) values ('Lotstring', 1, 6013);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 1, 2902);
insert into menu (menu_name, store_id, price) values ('Redhold', 2, 8585);
insert into menu (menu_name, store_id, price) values ('Alpha', 7, 7351);
insert into menu (menu_name, store_id, price) values ('Latlux', 6, 5605);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 9, 4317);
insert into menu (menu_name, store_id, price) values ('Matsoft', 11, 5683);
insert into menu (menu_name, store_id, price) values ('Bamity', 10, 9612);
insert into menu (menu_name, store_id, price) values ('Domainer', 4, 5083);
insert into menu (menu_name, store_id, price) values ('Cardguard', 17, 4597);
insert into menu (menu_name, store_id, price) values ('Stim', 8, 3295);
insert into menu (menu_name, store_id, price) values ('Alpha', 13, 2993);
insert into menu (menu_name, store_id, price) values ('Fintone', 4, 8189);
insert into menu (menu_name, store_id, price) values ('Konklux', 1, 4042);
insert into menu (menu_name, store_id, price) values ('Span', 4, 9162);
insert into menu (menu_name, store_id, price) values ('Tin', 13, 714);
insert into menu (menu_name, store_id, price) values ('Konklab', 10, 1944);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 10, 4309);
insert into menu (menu_name, store_id, price) values ('Gembucket', 19, 6444);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 19, 4075);
insert into menu (menu_name, store_id, price) values ('Trippledex', 1, 5972);
insert into menu (menu_name, store_id, price) values ('Temp', 15, 1818);
insert into menu (menu_name, store_id, price) values ('Andalax', 10, 1118);
insert into menu (menu_name, store_id, price) values ('Ronstring', 12, 1264);
insert into menu (menu_name, store_id, price) values ('Rank', 1, 5104);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 12, 4282);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 15, 6134);
insert into menu (menu_name, store_id, price) values ('Keylex', 2, 4837);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 1, 9685);
insert into menu (menu_name, store_id, price) values ('Job', 16, 8487);
insert into menu (menu_name, store_id, price) values ('Daltfresh', 2, 8834);
insert into menu (menu_name, store_id, price) values ('Cookley', 2, 6927);
insert into menu (menu_name, store_id, price) values ('Zathin', 1, 6518);
insert into menu (menu_name, store_id, price) values ('Konklux', 13, 9226);
insert into menu (menu_name, store_id, price) values ('Tresom', 5, 3797);
insert into menu (menu_name, store_id, price) values ('Fix San', 12, 1359);
insert into menu (menu_name, store_id, price) values ('Pannier', 1, 4737);
insert into menu (menu_name, store_id, price) values ('Treeflex', 9, 5536);
insert into menu (menu_name, store_id, price) values ('Gembucket', 11, 6391);
insert into menu (menu_name, store_id, price) values ('Zoolab', 19, 1390);
insert into menu (menu_name, store_id, price) values ('Gembucket', 8, 1252);
insert into menu (menu_name, store_id, price) values ('Lotlux', 7, 601);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 11, 4694);
insert into menu (menu_name, store_id, price) values ('Regrant', 19, 1963);
insert into menu (menu_name, store_id, price) values ('Transcof', 6, 7528);
insert into menu (menu_name, store_id, price) values ('Hatity', 11, 2939);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 3, 6585);
insert into menu (menu_name, store_id, price) values ('Cookley', 17, 5874);
insert into menu (menu_name, store_id, price) values ('Stringtough', 15, 8193);
insert into menu (menu_name, store_id, price) values ('Subin', 17, 5029);
insert into menu (menu_name, store_id, price) values ('Stim', 2, 8899);
insert into menu (menu_name, store_id, price) values ('Zamit', 4, 9275);
insert into menu (menu_name, store_id, price) values ('Sonsing', 2, 4308);
insert into menu (menu_name, store_id, price) values ('Zathin', 19, 3610);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 18, 2435);
insert into menu (menu_name, store_id, price) values ('Veribet', 7, 4319);
insert into menu (menu_name, store_id, price) values ('Sonsing', 8, 9281);
insert into menu (menu_name, store_id, price) values ('Zathin', 12, 653);
insert into menu (menu_name, store_id, price) values ('Bigtax', 2, 1783);
insert into menu (menu_name, store_id, price) values ('Opela', 16, 2649);
insert into menu (menu_name, store_id, price) values ('Job', 1, 3744);
insert into menu (menu_name, store_id, price) values ('Bigtax', 5, 3377);
insert into menu (menu_name, store_id, price) values ('Stim', 2, 169);
insert into menu (menu_name, store_id, price) values ('Rank', 6, 5613);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 14, 8132);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 8, 2234);
insert into menu (menu_name, store_id, price) values ('Matsoft', 7, 7959);
insert into menu (menu_name, store_id, price) values ('Regrant', 1, 4140);
insert into menu (menu_name, store_id, price) values ('Tin', 5, 6801);
insert into menu (menu_name, store_id, price) values ('Namfix', 6, 9042);
insert into menu (menu_name, store_id, price) values ('Zoolab', 2, 8015);
insert into menu (menu_name, store_id, price) values ('Greenlam', 14, 6256);
insert into menu (menu_name, store_id, price) values ('Domainer', 11, 7644);
insert into menu (menu_name, store_id, price) values ('Y-find', 16, 2136);
insert into menu (menu_name, store_id, price) values ('Ronstring', 11, 1104);
insert into menu (menu_name, store_id, price) values ('Treeflex', 15, 7510);
insert into menu (menu_name, store_id, price) values ('Vagram', 6, 7603);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 9, 6622);
insert into menu (menu_name, store_id, price) values ('Andalax', 5, 1289);
insert into menu (menu_name, store_id, price) values ('Temp', 10, 3782);
insert into menu (menu_name, store_id, price) values ('Konklab', 13, 6799);
insert into menu (menu_name, store_id, price) values ('Andalax', 19, 8959);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 17, 5048);
insert into menu (menu_name, store_id, price) values ('Alpha', 5, 3113);
insert into menu (menu_name, store_id, price) values ('Regrant', 8, 3799);
insert into menu (menu_name, store_id, price) values ('Cardify', 18, 517);
insert into menu (menu_name, store_id, price) values ('Andalax', 6, 8834);
insert into menu (menu_name, store_id, price) values ('Aerified', 19, 1230);
insert into menu (menu_name, store_id, price) values ('Overhold', 17, 9465);
insert into menu (menu_name, store_id, price) values ('Fixflex', 19, 4520);
insert into menu (menu_name, store_id, price) values ('Domainer', 4, 9257);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 17, 3722);
insert into menu (menu_name, store_id, price) values ('Regrant', 4, 8907);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 14, 3616);
insert into menu (menu_name, store_id, price) values ('Otcom', 13, 667);
insert into menu (menu_name, store_id, price) values ('Treeflex', 17, 138);
insert into menu (menu_name, store_id, price) values ('Alphazap', 3, 4669);
insert into menu (menu_name, store_id, price) values ('Temp', 11, 2812);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 9, 1336);
insert into menu (menu_name, store_id, price) values ('Stronghold', 4, 4901);
insert into menu (menu_name, store_id, price) values ('Bigtax', 9, 6170);
insert into menu (menu_name, store_id, price) values ('Fixflex', 14, 2057);
insert into menu (menu_name, store_id, price) values ('Latlux', 15, 7407);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 10, 7604);
insert into menu (menu_name, store_id, price) values ('Rank', 18, 2155);
insert into menu (menu_name, store_id, price) values ('Rank', 7, 4591);
insert into menu (menu_name, store_id, price) values ('Andalax', 7, 2682);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 5, 2153);
insert into menu (menu_name, store_id, price) values ('Opela', 4, 4105);
insert into menu (menu_name, store_id, price) values ('Zoolab', 13, 1675);
insert into menu (menu_name, store_id, price) values ('Prodder', 7, 8993);
insert into menu (menu_name, store_id, price) values ('Veribet', 13, 8387);
insert into menu (menu_name, store_id, price) values ('Biodex', 12, 3862);
insert into menu (menu_name, store_id, price) values ('Lotstring', 18, 6167);
insert into menu (menu_name, store_id, price) values ('Viva', 7, 9674);
insert into menu (menu_name, store_id, price) values ('Cookley', 1, 5127);
insert into menu (menu_name, store_id, price) values ('Span', 11, 8127);
insert into menu (menu_name, store_id, price) values ('Gembucket', 19, 1235);
insert into menu (menu_name, store_id, price) values ('Duobam', 3, 4269);
insert into menu (menu_name, store_id, price) values ('Ventosanzap', 7, 3244);
insert into menu (menu_name, store_id, price) values ('Prodder', 3, 3773);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 12, 3010);
insert into menu (menu_name, store_id, price) values ('Tampflex', 16, 1036);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 11, 6477);
insert into menu (menu_name, store_id, price) values ('Tampflex', 5, 3052);
insert into menu (menu_name, store_id, price) values ('Latlux', 11, 385);
insert into menu (menu_name, store_id, price) values ('Bamity', 1, 2677);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 18, 5382);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 1, 1182);
insert into menu (menu_name, store_id, price) values ('Bitchip', 14, 6301);
insert into menu (menu_name, store_id, price) values ('Mat Lam Tam', 1, 9536);
insert into menu (menu_name, store_id, price) values ('It', 4, 3407);
insert into menu (menu_name, store_id, price) values ('Asoka', 6, 3549);
insert into menu (menu_name, store_id, price) values ('Solarbreeze', 10, 8409);
insert into menu (menu_name, store_id, price) values ('Bamity', 1, 5507);
insert into menu (menu_name, store_id, price) values ('Matsoft', 5, 6357);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 18, 7636);
insert into menu (menu_name, store_id, price) values ('Sonair', 15, 7441);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 9, 7567);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 4, 1884);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 5, 3703);
insert into menu (menu_name, store_id, price) values ('Andalax', 10, 3640);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 5, 2703);
insert into menu (menu_name, store_id, price) values ('Zoolab', 8, 5536);
insert into menu (menu_name, store_id, price) values ('Alpha', 12, 1653);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 15, 1878);
insert into menu (menu_name, store_id, price) values ('Andalax', 9, 1140);
insert into menu (menu_name, store_id, price) values ('Kanlam', 12, 2513);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 16, 4941);
insert into menu (menu_name, store_id, price) values ('Treeflex', 15, 827);
insert into menu (menu_name, store_id, price) values ('Overhold', 1, 6407);
insert into menu (menu_name, store_id, price) values ('Latlux', 18, 3493);
insert into menu (menu_name, store_id, price) values ('Sub-Ex', 8, 247);
insert into menu (menu_name, store_id, price) values ('Konklux', 11, 2714);
insert into menu (menu_name, store_id, price) values ('Y-find', 2, 2926);
insert into menu (menu_name, store_id, price) values ('Konklab', 7, 3774);
insert into menu (menu_name, store_id, price) values ('Latlux', 17, 4514);
insert into menu (menu_name, store_id, price) values ('Bitchip', 13, 8674);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 19, 216);
insert into menu (menu_name, store_id, price) values ('Pannier', 19, 1524);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 11, 8469);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 10, 5216);
insert into menu (menu_name, store_id, price) values ('Prodder', 19, 2339);
insert into menu (menu_name, store_id, price) values ('Quo Lux', 11, 3105);
insert into menu (menu_name, store_id, price) values ('Stringtough', 1, 3062);
insert into menu (menu_name, store_id, price) values ('Tempsoft', 9, 9598);
insert into menu (menu_name, store_id, price) values ('Hatity', 15, 1400);
insert into menu (menu_name, store_id, price) values ('Wrapsafe', 15, 2260);
insert into menu (menu_name, store_id, price) values ('Zaam-Dox', 17, 1319);
insert into menu (menu_name, store_id, price) values ('Pannier', 10, 7514);
insert into menu (menu_name, store_id, price) values ('Matsoft', 12, 2309);
insert into menu (menu_name, store_id, price) values ('Viva', 19, 2152);
insert into menu (menu_name, store_id, price) values ('Trippledex', 15, 6993);
insert into menu (menu_name, store_id, price) values ('Flexidy', 1, 9645);
insert into menu (menu_name, store_id, price) values ('Duobam', 13, 6934);
insert into menu (menu_name, store_id, price) values ('Aerified', 10, 2551);
insert into menu (menu_name, store_id, price) values ('Bigtax', 8, 7564);
insert into menu (menu_name, store_id, price) values ('Zamit', 19, 8028);
insert into menu (menu_name, store_id, price) values ('Voltsillam', 9, 9153);
insert into menu (menu_name, store_id, price) values ('Pannier', 6, 4382);
insert into menu (menu_name, store_id, price) values ('Zathin', 1, 7604);
insert into menu (menu_name, store_id, price) values ('Prodder', 7, 7578);
insert into menu (menu_name, store_id, price) values ('Span', 18, 9233);
insert into menu (menu_name, store_id, price) values ('Opela', 12, 3256);
insert into menu (menu_name, store_id, price) values ('Stim', 14, 5871);
insert into menu (menu_name, store_id, price) values ('Prodder', 15, 6826);
insert into menu (menu_name, store_id, price) values ('Fintone', 14, 1167);
insert into menu (menu_name, store_id, price) values ('Konklux', 14, 6362);
insert into menu (menu_name, store_id, price) values ('Pannier', 7, 3493);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 14, 3621);
insert into menu (menu_name, store_id, price) values ('Otcom', 2, 468);
insert into menu (menu_name, store_id, price) values ('Subin', 18, 4852);
insert into menu (menu_name, store_id, price) values ('Redhold', 12, 4496);
insert into menu (menu_name, store_id, price) values ('Bitchip', 12, 8541);
insert into menu (menu_name, store_id, price) values ('Vagram', 13, 7011);
insert into menu (menu_name, store_id, price) values ('Asoka', 19, 4714);
insert into menu (menu_name, store_id, price) values ('Treeflex', 9, 8276);
insert into menu (menu_name, store_id, price) values ('Tin', 13, 778);
insert into menu (menu_name, store_id, price) values ('Viva', 8, 8543);
insert into menu (menu_name, store_id, price) values ('Y-Solowarm', 4, 7077);
insert into menu (menu_name, store_id, price) values ('Tresom', 8, 4530);
insert into menu (menu_name, store_id, price) values ('Cookley', 19, 4058);
insert into menu (menu_name, store_id, price) values ('Lotstring', 1, 1596);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 7, 2389);
insert into menu (menu_name, store_id, price) values ('Zontrax', 6, 5131);
insert into menu (menu_name, store_id, price) values ('Y-find', 10, 3999);
insert into menu (menu_name, store_id, price) values ('Tresom', 2, 3102);
insert into menu (menu_name, store_id, price) values ('Bitwolf', 5, 4930);
insert into menu (menu_name, store_id, price) values ('Alpha', 1, 7237);
insert into menu (menu_name, store_id, price) values ('Temp', 10, 8000);
insert into menu (menu_name, store_id, price) values ('Cardify', 15, 8999);
insert into menu (menu_name, store_id, price) values ('Toughjoyfax', 16, 6115);
insert into menu (menu_name, store_id, price) values ('Flowdesk', 18, 3459);
insert into menu (menu_name, store_id, price) values ('Andalax', 5, 2504);
insert into menu (menu_name, store_id, price) values ('Stringtough', 11, 7965);
insert into menu (menu_name, store_id, price) values ('Domainer', 5, 573);
insert into menu (menu_name, store_id, price) values ('Fintone', 16, 9056);
insert into menu (menu_name, store_id, price) values ('Latlux', 17, 2347);
insert into menu (menu_name, store_id, price) values ('Span', 14, 5034);
insert into menu (menu_name, store_id, price) values ('Otcom', 11, 2832);
insert into menu (menu_name, store_id, price) values ('Tres-Zap', 12, 4872);
insert into menu (menu_name, store_id, price) values ('Holdlamis', 1, 8555);



