
select * from store;

select * from pos_order;

insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Edgepulse', 40.5235837, 19.8075358, 'aa', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Mydo', -27.0052075, -51.154395, 'bb', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Shufflebeat', 12.2328311, 107.6216789, 'cc', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Skaboo', 43.4676913, 19.8125507, 'dd', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Abata', 40.211601, 46.8237055, 'ee', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Jabbersphere', 14.5403397, 121.0268687, 'ff', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Photobug', -7.0543824, 108.7690065, 'gg', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Dablist', 55.4763949, 13.5019331, 'hh', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Podcat', 34.8291055, 36.2264681, 'ii', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Centidel', 38.8424265, -9.1901989, 'jj', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Zooxo', 49.05798, -122.25257, 'kk', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Thoughtbeat', 11.9210864, -86.1230153, 'll', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('InnoZ', 51.349366, 9.7730968, 'mm', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Dabtype', -29.5904737, -51.3738524, 'nn', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Jabberbean', 15.3083007, 47.9787391, 'oo', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Tagfeed', 59.927607, 32.296821, 'pp', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Yabox', 26.8429645, 107.2902839, 'qq', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Realcube', 38.64501, 65.68952, 'rr', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Plajo', 28.5107872, -81.4828198, 'ss', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');
insert into store (store_name, latitude, longitude, store_login_id, store_login_pw) values ('Katz', -8.6450837, 116.8085683, 'tt', '$2a$10$eQxwZAhVtJa2bGjJRbLYyOk2cUTEW.6Xfg7ziQsYoRLlE8BcOfEbS');

insert into category (category_name, store_id) values ('메인', 1);
insert into category (category_name, store_id) values ('사이드', 1);
insert into category (category_name, store_id) values ('메인', 2);
insert into category (category_name, store_id) values ('사이드', 2);
insert into category (category_name, store_id) values ('메인', 3);
insert into category (category_name, store_id) values ('사이드', 3);
insert into category (category_name, store_id) values ('메인', 4);
insert into category (category_name, store_id) values ('사이드', 4);
insert into category (category_name, store_id) values ('메인', 5);
insert into category (category_name, store_id) values ('사이드', 5);
insert into category (category_name, store_id) values ('메인', 6);
insert into category (category_name, store_id) values ('사이드', 6);
insert into category (category_name, store_id) values ('메인', 7);
insert into category (category_name, store_id) values ('사이드', 7);
insert into category (category_name, store_id) values ('메인', 8);
insert into category (category_name, store_id) values ('사이드', 8);
insert into category (category_name, store_id) values ('메인', 9);
insert into category (category_name, store_id) values ('사이드', 9);
insert into category (category_name, store_id) values ('메인', 10);
insert into category (category_name, store_id) values ('사이드', 10);
insert into category (category_name, store_id) values ('메인', 11);
insert into category (category_name, store_id) values ('사이드', 11);
insert into category (category_name, store_id) values ('메인', 12);
insert into category (category_name, store_id) values ('사이드', 12);
insert into category (category_name, store_id) values ('메인', 13);
insert into category (category_name, store_id) values ('사이드', 13);
insert into category (category_name, store_id) values ('메인', 14);
insert into category (category_name, store_id) values ('사이드', 14);
insert into category (category_name, store_id) values ('메인', 15);
insert into category (category_name, store_id) values ('사이드', 15);
insert into category (category_name, store_id) values ('메인', 16);
insert into category (category_name, store_id) values ('사이드', 16);
insert into category (category_name, store_id) values ('메인', 17);
insert into category (category_name, store_id) values ('사이드', 17);
insert into category (category_name, store_id) values ('메인', 18);
insert into category (category_name, store_id) values ('사이드', 18);
insert into category (category_name, store_id) values ('메인', 19);
insert into category (category_name, store_id) values ('사이드', 19);
insert into category (category_name, store_id) values ('메인', 20);
insert into category (category_name, store_id) values ('사이드', 20);

insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 17, 33, 58898);
insert into menu (menu_name, store_id, category_id, price) values ('Bytecard', 13, 26, 86806);
insert into menu (menu_name, store_id, category_id, price) values ('Quo Lux', 12, 24, 61770);
insert into menu (menu_name, store_id, category_id, price) values ('Regrant', 4, 8, 99297);
insert into menu (menu_name, store_id, category_id, price) values ('Domainer', 11, 22, 88742);
insert into menu (menu_name, store_id, category_id, price) values ('Zamit', 12, 23, 56079);
insert into menu (menu_name, store_id, category_id, price) values ('Bytecard', 2, 4, 82462);
insert into menu (menu_name, store_id, category_id, price) values ('Domainer', 11, 22, 66640);
insert into menu (menu_name, store_id, category_id, price) values ('Prodder', 12, 24, 18237);
insert into menu (menu_name, store_id, category_id, price) values ('Tres-Zap', 13, 25, 77671);
insert into menu (menu_name, store_id, category_id, price) values ('Voyatouch', 9, 18, 55153);
insert into menu (menu_name, store_id, category_id, price) values ('Sonair', 12, 24, 99733);
insert into menu (menu_name, store_id, category_id, price) values ('Vagram', 11, 21, 92628);
insert into menu (menu_name, store_id, category_id, price) values ('Voyatouch', 4, 7, 8923);
insert into menu (menu_name, store_id, category_id, price) values ('Quo Lux', 1, 2, 30511);
insert into menu (menu_name, store_id, category_id, price) values ('Gembucket', 17, 33, 87787);
insert into menu (menu_name, store_id, category_id, price) values ('Viva', 13, 26, 91904);
insert into menu (menu_name, store_id, category_id, price) values ('Veribet', 11, 21, 2408);
insert into menu (menu_name, store_id, category_id, price) values ('Bigtax', 18, 36, 35325);
insert into menu (menu_name, store_id, category_id, price) values ('Alphazap', 18, 35, 62605);
insert into menu (menu_name, store_id, category_id, price) values ('Sonair', 6, 12, 6603);
insert into menu (menu_name, store_id, category_id, price) values ('Fixflex', 16, 31, 99730);
insert into menu (menu_name, store_id, category_id, price) values ('Voyatouch', 1, 1, 23598);
insert into menu (menu_name, store_id, category_id, price) values ('Zathin', 8, 16, 15192);
insert into menu (menu_name, store_id, category_id, price) values ('Toughjoyfax', 1, 2, 68682);
insert into menu (menu_name, store_id, category_id, price) values ('Holdlamis', 3, 6, 70673);
insert into menu (menu_name, store_id, category_id, price) values ('Transcof', 9, 17, 3609);
insert into menu (menu_name, store_id, category_id, price) values ('Zontrax', 17, 34, 62669);
insert into menu (menu_name, store_id, category_id, price) values ('Quo Lux', 10, 20, 69387);
insert into menu (menu_name, store_id, category_id, price) values ('Ventosanzap', 10, 20, 92893);
insert into menu (menu_name, store_id, category_id, price) values ('Bitwolf', 17, 34, 12973);
insert into menu (menu_name, store_id, category_id, price) values ('Ronstring', 5, 9, 36083);
insert into menu (menu_name, store_id, category_id, price) values ('Alpha', 16, 31, 65883);
insert into menu (menu_name, store_id, category_id, price) values ('Sonsing', 16, 32, 10474);
insert into menu (menu_name, store_id, category_id, price) values ('Voltsillam', 19, 37, 24697);
insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 10, 20, 99175);
insert into menu (menu_name, store_id, category_id, price) values ('Zamit', 9, 18, 53865);
insert into menu (menu_name, store_id, category_id, price) values ('Treeflex', 7, 13, 52280);
insert into menu (menu_name, store_id, category_id, price) values ('Lotstring', 3, 6, 76004);
insert into menu (menu_name, store_id, category_id, price) values ('Home Ing', 6, 11, 8482);
insert into menu (menu_name, store_id, category_id, price) values ('Solarbreeze', 13, 25, 62407);
insert into menu (menu_name, store_id, category_id, price) values ('Tin', 2, 4, 79960);
insert into menu (menu_name, store_id, category_id, price) values ('Y-Solowarm', 10, 19, 11588);
insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 12, 24, 12538);
insert into menu (menu_name, store_id, category_id, price) values ('Ventosanzap', 16, 32, 74515);
insert into menu (menu_name, store_id, category_id, price) values ('Hatity', 15, 30, 50869);
insert into menu (menu_name, store_id, category_id, price) values ('Zontrax', 8, 15, 71892);
insert into menu (menu_name, store_id, category_id, price) values ('Fix San', 1, 2, 97286);
insert into menu (menu_name, store_id, category_id, price) values ('Subin', 6, 11, 49259);
insert into menu (menu_name, store_id, category_id, price) values ('Holdlamis', 20, 40, 70597);
insert into menu (menu_name, store_id, category_id, price) values ('Temp', 18, 36, 41362);
insert into menu (menu_name, store_id, category_id, price) values ('Home Ing', 8, 16, 87664);
insert into menu (menu_name, store_id, category_id, price) values ('Viva', 2, 4, 4942);
insert into menu (menu_name, store_id, category_id, price) values ('Tampflex', 13, 25, 68174);
insert into menu (menu_name, store_id, category_id, price) values ('Rank', 11, 22, 40814);
insert into menu (menu_name, store_id, category_id, price) values ('Duobam', 11, 21, 4090);
insert into menu (menu_name, store_id, category_id, price) values ('Stronghold', 2, 4, 18090);
insert into menu (menu_name, store_id, category_id, price) values ('Span', 6, 12, 33810);
insert into menu (menu_name, store_id, category_id, price) values ('Konklux', 17, 34, 80349);
insert into menu (menu_name, store_id, category_id, price) values ('Subin', 11, 22, 26136);
insert into menu (menu_name, store_id, category_id, price) values ('Job', 15, 29, 42584);
insert into menu (menu_name, store_id, category_id, price) values ('Zamit', 17, 34, 45497);
insert into menu (menu_name, store_id, category_id, price) values ('Prodder', 12, 23, 44505);
insert into menu (menu_name, store_id, category_id, price) values ('Voltsillam', 4, 8, 78599);
insert into menu (menu_name, store_id, category_id, price) values ('Stronghold', 17, 33, 38987);
insert into menu (menu_name, store_id, category_id, price) values ('Voltsillam', 7, 13, 34268);
insert into menu (menu_name, store_id, category_id, price) values ('Rank', 8, 16, 15602);
insert into menu (menu_name, store_id, category_id, price) values ('Quo Lux', 9, 18, 8058);
insert into menu (menu_name, store_id, category_id, price) values ('Aerified', 19, 37, 86560);
insert into menu (menu_name, store_id, category_id, price) values ('Matsoft', 5, 9, 90701);
insert into menu (menu_name, store_id, category_id, price) values ('Flowdesk', 3, 6, 89924);
insert into menu (menu_name, store_id, category_id, price) values ('Temp', 10, 19, 86664);
insert into menu (menu_name, store_id, category_id, price) values ('Gembucket', 18, 35, 10966);
insert into menu (menu_name, store_id, category_id, price) values ('Konklux', 15, 30, 59488);
insert into menu (menu_name, store_id, category_id, price) values ('Pannier', 19, 38, 99638);
insert into menu (menu_name, store_id, category_id, price) values ('Mat Lam Tam', 20, 40, 84911);
insert into menu (menu_name, store_id, category_id, price) values ('Asoka', 18, 36, 13668);
insert into menu (menu_name, store_id, category_id, price) values ('Konklab', 18, 36, 96429);
insert into menu (menu_name, store_id, category_id, price) values ('Treeflex', 19, 37, 80290);
insert into menu (menu_name, store_id, category_id, price) values ('Y-find', 16, 32, 70137);
insert into menu (menu_name, store_id, category_id, price) values ('Home Ing', 19, 38, 39080);
insert into menu (menu_name, store_id, category_id, price) values ('Konklux', 13, 25, 21467);
insert into menu (menu_name, store_id, category_id, price) values ('Tempsoft', 9, 18, 72480);
insert into menu (menu_name, store_id, category_id, price) values ('Namfix', 19, 37, 35940);
insert into menu (menu_name, store_id, category_id, price) values ('Regrant', 10, 20, 95067);
insert into menu (menu_name, store_id, category_id, price) values ('Ventosanzap', 3, 5, 61304);
insert into menu (menu_name, store_id, category_id, price) values ('Y-Solowarm', 17, 33, 7856);
insert into menu (menu_name, store_id, category_id, price) values ('Voyatouch', 13, 26, 62338);
insert into menu (menu_name, store_id, category_id, price) values ('Rank', 8, 16, 80609);
insert into menu (menu_name, store_id, category_id, price) values ('Zathin', 18, 35, 69268);
insert into menu (menu_name, store_id, category_id, price) values ('Treeflex', 11, 21, 16479);
insert into menu (menu_name, store_id, category_id, price) values ('Veribet', 12, 24, 58784);
insert into menu (menu_name, store_id, category_id, price) values ('It', 19, 38, 14402);
insert into menu (menu_name, store_id, category_id, price) values ('Ronstring', 8, 15, 59302);
insert into menu (menu_name, store_id, category_id, price) values ('Bamity', 13, 26, 74219);
insert into menu (menu_name, store_id, category_id, price) values ('Bytecard', 7, 13, 84756);
insert into menu (menu_name, store_id, category_id, price) values ('Job', 18, 35, 14078);
insert into menu (menu_name, store_id, category_id, price) values ('Rank', 5, 10, 51843);
insert into menu (menu_name, store_id, category_id, price) values ('Cardify', 5, 10, 75653);
insert into menu (menu_name, store_id, category_id, price) values ('Domainer', 1, 1, 12084);
insert into menu (menu_name, store_id, category_id, price) values ('Y-Solowarm', 11, 22, 49435);
insert into menu (menu_name, store_id, category_id, price) values ('Duobam', 3, 6, 76217);
insert into menu (menu_name, store_id, category_id, price) values ('Overhold', 14, 27, 65567);
insert into menu (menu_name, store_id, category_id, price) values ('Toughjoyfax', 1, 2, 43584);
insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 5, 10, 79486);
insert into menu (menu_name, store_id, category_id, price) values ('Konklux', 16, 32, 71043);
insert into menu (menu_name, store_id, category_id, price) values ('Lotlux', 16, 31, 40625);
insert into menu (menu_name, store_id, category_id, price) values ('Duobam', 14, 28, 27697);
insert into menu (menu_name, store_id, category_id, price) values ('Bitchip', 15, 30, 37686);
insert into menu (menu_name, store_id, category_id, price) values ('Redhold', 5, 10, 77923);
insert into menu (menu_name, store_id, category_id, price) values ('Biodex', 8, 15, 29946);
insert into menu (menu_name, store_id, category_id, price) values ('Job', 11, 21, 2741);
insert into menu (menu_name, store_id, category_id, price) values ('Veribet', 19, 38, 52741);
insert into menu (menu_name, store_id, category_id, price) values ('Treeflex', 12, 24, 42692);
insert into menu (menu_name, store_id, category_id, price) values ('Fixflex', 15, 29, 28212);
insert into menu (menu_name, store_id, category_id, price) values ('Lotstring', 20, 40, 37066);
insert into menu (menu_name, store_id, category_id, price) values ('Tresom', 6, 12, 16499);
insert into menu (menu_name, store_id, category_id, price) values ('Matsoft', 6, 11, 47797);
insert into menu (menu_name, store_id, category_id, price) values ('Mat Lam Tam', 3, 6, 52909);
insert into menu (menu_name, store_id, category_id, price) values ('Mat Lam Tam', 5, 10, 49823);
insert into menu (menu_name, store_id, category_id, price) values ('Tin', 8, 15, 96493);
insert into menu (menu_name, store_id, category_id, price) values ('Gembucket', 20, 39, 55825);
insert into menu (menu_name, store_id, category_id, price) values ('Fixflex', 6, 12, 57488);
insert into menu (menu_name, store_id, category_id, price) values ('Subin', 14, 27, 48431);
insert into menu (menu_name, store_id, category_id, price) values ('Bigtax', 7, 13, 47010);
insert into menu (menu_name, store_id, category_id, price) values ('Namfix', 15, 29, 34355);
insert into menu (menu_name, store_id, category_id, price) values ('Sonsing', 11, 21, 24010);
insert into menu (menu_name, store_id, category_id, price) values ('Zontrax', 20, 40, 31276);
insert into menu (menu_name, store_id, category_id, price) values ('Stronghold', 10, 19, 93077);
insert into menu (menu_name, store_id, category_id, price) values ('Fixflex', 10, 20, 17221);
insert into menu (menu_name, store_id, category_id, price) values ('Job', 13, 25, 32866);
insert into menu (menu_name, store_id, category_id, price) values ('Alphazap', 11, 22, 58586);
insert into menu (menu_name, store_id, category_id, price) values ('Konklab', 2, 4, 47343);
insert into menu (menu_name, store_id, category_id, price) values ('Zontrax', 19, 37, 85383);
insert into menu (menu_name, store_id, category_id, price) values ('Solarbreeze', 19, 38, 40627);
insert into menu (menu_name, store_id, category_id, price) values ('Sub-Ex', 15, 29, 55394);
insert into menu (menu_name, store_id, category_id, price) values ('Kanlam', 3, 6, 52225);
insert into menu (menu_name, store_id, category_id, price) values ('Opela', 19, 37, 3117);
insert into menu (menu_name, store_id, category_id, price) values ('Y-find', 9, 18, 27731);
insert into menu (menu_name, store_id, category_id, price) values ('Biodex', 13, 26, 56781);
insert into menu (menu_name, store_id, category_id, price) values ('Tresom', 14, 28, 19331);
insert into menu (menu_name, store_id, category_id, price) values ('Sonair', 12, 24, 44812);
insert into menu (menu_name, store_id, category_id, price) values ('Bamity', 12, 24, 4344);
insert into menu (menu_name, store_id, category_id, price) values ('Regrant', 8, 15, 81625);
insert into menu (menu_name, store_id, category_id, price) values ('Fix San', 16, 32, 57380);
insert into menu (menu_name, store_id, category_id, price) values ('Mat Lam Tam', 1, 2, 89756);
insert into menu (menu_name, store_id, category_id, price) values ('Overhold', 19, 38, 17251);
insert into menu (menu_name, store_id, category_id, price) values ('Voyatouch', 1, 2, 71616);
insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 3, 6, 34044);
insert into menu (menu_name, store_id, category_id, price) values ('Stim', 6, 12, 24144);
insert into menu (menu_name, store_id, category_id, price) values ('Job', 18, 36, 87517);
insert into menu (menu_name, store_id, category_id, price) values ('Holdlamis', 15, 29, 15282);
insert into menu (menu_name, store_id, category_id, price) values ('Overhold', 15, 30, 79992);
insert into menu (menu_name, store_id, category_id, price) values ('Y-Solowarm', 18, 36, 80459);
insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 1, 2, 87655);
insert into menu (menu_name, store_id, category_id, price) values ('Greenlam', 18, 36, 26322);
insert into menu (menu_name, store_id, category_id, price) values ('Gembucket', 7, 13, 26444);
insert into menu (menu_name, store_id, category_id, price) values ('Voyatouch', 20, 39, 43081);
insert into menu (menu_name, store_id, category_id, price) values ('Subin', 3, 5, 42874);
insert into menu (menu_name, store_id, category_id, price) values ('Voyatouch', 17, 33, 84507);
insert into menu (menu_name, store_id, category_id, price) values ('Bamity', 2, 3, 53796);
insert into menu (menu_name, store_id, category_id, price) values ('Tres-Zap', 15, 30, 25768);
insert into menu (menu_name, store_id, category_id, price) values ('Tempsoft', 9, 17, 39958);
insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 2, 4, 43940);
insert into menu (menu_name, store_id, category_id, price) values ('Rank', 16, 31, 32091);
insert into menu (menu_name, store_id, category_id, price) values ('Otcom', 11, 22, 51409);
insert into menu (menu_name, store_id, category_id, price) values ('Aerified', 3, 5, 33844);
insert into menu (menu_name, store_id, category_id, price) values ('Cardguard', 7, 13, 37227);
insert into menu (menu_name, store_id, category_id, price) values ('Vagram', 16, 32, 88559);
insert into menu (menu_name, store_id, category_id, price) values ('Sonair', 1, 2, 32289);
insert into menu (menu_name, store_id, category_id, price) values ('Solarbreeze', 5, 9, 15000);
insert into menu (menu_name, store_id, category_id, price) values ('Hatity', 18, 35, 19104);
insert into menu (menu_name, store_id, category_id, price) values ('Kanlam', 6, 12, 77251);
insert into menu (menu_name, store_id, category_id, price) values ('Latlux', 8, 15, 60572);
insert into menu (menu_name, store_id, category_id, price) values ('Bitwolf', 2, 4, 65410);
insert into menu (menu_name, store_id, category_id, price) values ('Home Ing', 18, 36, 93024);
insert into menu (menu_name, store_id, category_id, price) values ('Zoolab', 2, 4, 84448);
insert into menu (menu_name, store_id, category_id, price) values ('Opela', 19, 38, 64868);
insert into menu (menu_name, store_id, category_id, price) values ('Span', 4, 7, 76722);
insert into menu (menu_name, store_id, category_id, price) values ('Transcof', 5, 9, 32495);
insert into menu (menu_name, store_id, category_id, price) values ('Otcom', 9, 18, 32640);
insert into menu (menu_name, store_id, category_id, price) values ('Quo Lux', 7, 14, 62992);
insert into menu (menu_name, store_id, category_id, price) values ('Y-find', 9, 17, 92608);
insert into menu (menu_name, store_id, category_id, price) values ('Span', 2, 3, 86981);
insert into menu (menu_name, store_id, category_id, price) values ('Overhold', 11, 22, 75750);
insert into menu (menu_name, store_id, category_id, price) values ('Transcof', 16, 31, 36309);
insert into menu (menu_name, store_id, category_id, price) values ('Voltsillam', 6, 12, 50754);
insert into menu (menu_name, store_id, category_id, price) values ('Matsoft', 17, 33, 9946);
insert into menu (menu_name, store_id, category_id, price) values ('Wrapsafe', 4, 7, 24981);
insert into menu (menu_name, store_id, category_id, price) values ('Sub-Ex', 4, 8, 90551);
insert into menu (menu_name, store_id, category_id, price) values ('Domainer', 7, 14, 21286);
insert into menu (menu_name, store_id, category_id, price) values ('Cardguard', 13, 26, 30324);
insert into menu (menu_name, store_id, category_id, price) values ('Home Ing', 14, 28, 1053);
insert into menu (menu_name, store_id, category_id, price) values ('Bigtax', 6, 11, 50827);
insert into menu (menu_name, store_id, category_id, price) values ('Biodex', 20, 39, 3184);
insert into menu (menu_name, store_id, category_id, price) values ('Lotlux', 4, 7, 40694);
insert into menu (menu_name, store_id, category_id, price) values ('Treeflex', 18, 36, 88888);
insert into menu (menu_name, store_id, category_id, price) values ('Cookley', 1, 2, 21943);
insert into menu (menu_name, store_id, category_id, price) values ('Konklab', 17, 33, 13708);
insert into menu (menu_name, store_id, category_id, price) values ('Ronstring', 9, 18, 72081);

insert into seat (seat_name, store_id) values (1, 18);
insert into seat (seat_name, store_id) values (2, 9);
insert into seat (seat_name, store_id) values (3, 18);
insert into seat (seat_name, store_id) values (4, 6);
insert into seat (seat_name, store_id) values (5, 4);
insert into seat (seat_name, store_id) values (6, 4);
insert into seat (seat_name, store_id) values (7, 5);
insert into seat (seat_name, store_id) values (8, 15);
insert into seat (seat_name, store_id) values (9, 7);
insert into seat (seat_name, store_id) values (10, 10);
insert into seat (seat_name, store_id) values (11, 6);
insert into seat (seat_name, store_id) values (12, 8);
insert into seat (seat_name, store_id) values (13, 1);
insert into seat (seat_name, store_id) values (14, 7);
insert into seat (seat_name, store_id) values (15, 8);
insert into seat (seat_name, store_id) values (16, 7);
insert into seat (seat_name, store_id) values (17, 19);
insert into seat (seat_name, store_id) values (18, 19);
insert into seat (seat_name, store_id) values (19, 4);
insert into seat (seat_name, store_id) values (20, 5);
insert into seat (seat_name, store_id) values (21, 11);
insert into seat (seat_name, store_id) values (22, 3);
insert into seat (seat_name, store_id) values (23, 3);
insert into seat (seat_name, store_id) values (24, 6);
insert into seat (seat_name, store_id) values (25, 19);
insert into seat (seat_name, store_id) values (26, 11);
insert into seat (seat_name, store_id) values (27, 13);
insert into seat (seat_name, store_id) values (28, 10);
insert into seat (seat_name, store_id) values (29, 4);
insert into seat (seat_name, store_id) values (30, 7);
insert into seat (seat_name, store_id) values (31, 17);
insert into seat (seat_name, store_id) values (32, 8);
insert into seat (seat_name, store_id) values (33, 4);
insert into seat (seat_name, store_id) values (34, 5);
insert into seat (seat_name, store_id) values (35, 11);
insert into seat (seat_name, store_id) values (36, 10);
insert into seat (seat_name, store_id) values (37, 14);
insert into seat (seat_name, store_id) values (38, 12);
insert into seat (seat_name, store_id) values (39, 2);
insert into seat (seat_name, store_id) values (40, 16);
insert into seat (seat_name, store_id) values (41, 10);
insert into seat (seat_name, store_id) values (42, 1);
insert into seat (seat_name, store_id) values (43, 11);
insert into seat (seat_name, store_id) values (44, 11);
insert into seat (seat_name, store_id) values (45, 8);
insert into seat (seat_name, store_id) values (46, 2);
insert into seat (seat_name, store_id) values (47, 9);
insert into seat (seat_name, store_id) values (48, 13);
insert into seat (seat_name, store_id) values (49, 20);
insert into seat (seat_name, store_id) values (50, 2);
insert into seat (seat_name, store_id) values (51, 8);
insert into seat (seat_name, store_id) values (52, 9);
insert into seat (seat_name, store_id) values (53, 11);
insert into seat (seat_name, store_id) values (54, 14);
insert into seat (seat_name, store_id) values (55, 9);
insert into seat (seat_name, store_id) values (56, 4);
insert into seat (seat_name, store_id) values (57, 1);
insert into seat (seat_name, store_id) values (58, 18);
insert into seat (seat_name, store_id) values (59, 10);
insert into seat (seat_name, store_id) values (60, 1);
insert into seat (seat_name, store_id) values (61, 7);
insert into seat (seat_name, store_id) values (62, 1);
insert into seat (seat_name, store_id) values (63, 11);
insert into seat (seat_name, store_id) values (64, 4);
insert into seat (seat_name, store_id) values (65, 5);
insert into seat (seat_name, store_id) values (66, 18);
insert into seat (seat_name, store_id) values (67, 17);
insert into seat (seat_name, store_id) values (68, 14);
insert into seat (seat_name, store_id) values (69, 9);
insert into seat (seat_name, store_id) values (70, 16);
insert into seat (seat_name, store_id) values (71, 2);
insert into seat (seat_name, store_id) values (72, 19);
insert into seat (seat_name, store_id) values (73, 13);
insert into seat (seat_name, store_id) values (74, 14);
insert into seat (seat_name, store_id) values (75, 11);
insert into seat (seat_name, store_id) values (76, 8);
insert into seat (seat_name, store_id) values (77, 13);
insert into seat (seat_name, store_id) values (78, 17);
insert into seat (seat_name, store_id) values (79, 13);
insert into seat (seat_name, store_id) values (80, 14);
insert into seat (seat_name, store_id) values (81, 10);
insert into seat (seat_name, store_id) values (82, 3);
insert into seat (seat_name, store_id) values (83, 19);
insert into seat (seat_name, store_id) values (84, 10);
insert into seat (seat_name, store_id) values (85, 4);
insert into seat (seat_name, store_id) values (86, 16);
insert into seat (seat_name, store_id) values (87, 2);
insert into seat (seat_name, store_id) values (88, 11);
insert into seat (seat_name, store_id) values (89, 13);
insert into seat (seat_name, store_id) values (90, 10);
insert into seat (seat_name, store_id) values (91, 12);
insert into seat (seat_name, store_id) values (92, 16);
insert into seat (seat_name, store_id) values (93, 15);
insert into seat (seat_name, store_id) values (94, 16);
insert into seat (seat_name, store_id) values (95, 8);
insert into seat (seat_name, store_id) values (96, 16);
insert into seat (seat_name, store_id) values (97, 14);
insert into seat (seat_name, store_id) values (98, 19);
insert into seat (seat_name, store_id) values (99, 17);
insert into seat (seat_name, store_id) values (100, 6);




